/* Auto-generated by spu_lifter.py -- do not edit by hand. */
#include "spu_recomp.h"
#include "../../runtime/spu/spu_helpers.h"


void spu_func_00000000(spu_context* ctx) {
        ctx->gpr[3] = spu_il(32767);
        ctx->gpr[4] = spu_il(32766);
        ctx->gpr[5] = spu_ilh(0xC0E0);
        ctx->gpr[6] = spu_shufb(ctx->gpr[3], ctx->gpr[4], ctx->gpr[5]);
        spu_wrch(ctx, SPU_WrOutMbox, ctx->gpr[6]);
        ctx->status = SPU_STATUS_STOPPED_BY_STOP; return;
}

/* Function table */
typedef struct { uint32_t addr; void (*func)(spu_context*); const char* name; } spu_func_entry;
static const spu_func_entry spu_function_table[] = {
    { 0x00000000u, spu_func_00000000, "spu_func_00000000" },
    { 0, NULL, NULL }
};

void spu_recomp_register(void) {
    for (const spu_func_entry* e = spu_function_table; e->func; ++e)
        spu_register_function(e->addr, e->func);
}
