/* Auto-generated by spu_lifter.py -- do not edit by hand. */
#include "spu_recomp.h"
#include "../../runtime/spu/spu_helpers.h"


void spu_func_00000000(spu_context* ctx) {
        ctx->gpr[11] = spu_il(16);
        ctx->gpr[2] = spu_shli(ctx->gpr[5], 4);
        ctx->gpr[2] = spu_shl(ctx->gpr[2], ctx->gpr[8]);
        ctx->gpr[8] = spu_shlqbi(ctx->gpr[11], ctx->gpr[8]);
        ctx->gpr[2] = spu_sfi(ctx->gpr[2], 0);
        ctx->gpr[9] = spu_shlqbi(ctx->gpr[11], ctx->gpr[9]);
        ctx->gpr[19] = spu_a(ctx->gpr[4], ctx->gpr[9]);
        ctx->gpr[23] = spu_a(ctx->gpr[19], ctx->gpr[9]);
        ctx->gpr[27] = spu_a(ctx->gpr[23], ctx->gpr[9]);
        ctx->gpr[8] = spu_shlqbii(ctx->gpr[8], 2);
        ctx->gpr[9] = spu_shlqbii(ctx->gpr[9], 2);
        ctx->gpr[12] = spu_il(0);
        ctx->gpr[14] = spu_il(0);
        ctx->gpr[13] = spu_il(4919);
        ctx->gpr[34] = spu_il(13364);
        ctx->gpr[35] = spu_il(13621);
        ctx->gpr[36] = spu_il(13878);
        ctx->gpr[15] = spu_ila(0x80);
        { ctx->pc = 0x80; g_spu_trampoline_fn = spu_func_00000080; return; }
        /* nop */;
        /* nop */;
        /* nop */;
        /* nop */;
        /* nop */;
        /* nop */;
        /* nop */;
        /* nop */;
        /* nop */;
        /* nop */;
        /* nop */;
        /* nop */;
        /* nop */;
        { ctx->pc = 0x80; g_spu_trampoline_fn = spu_func_00000080; return; }
}

void spu_func_00000080(spu_context* ctx) {
        ctx->gpr[37] = spu_ceqi(ctx->gpr[2], 0);
        spu_ls_write128(ctx, ctx->gpr[4]._u32[0] + ctx->gpr[12]._u32[0], ctx->gpr[13]);
        ctx->gpr[2] = spu_a(ctx->gpr[8], ctx->gpr[2]);
        spu_ls_write128(ctx, ctx->gpr[19]._u32[0] + ctx->gpr[12]._u32[0], ctx->gpr[34]);
        ctx->gpr[10] = spu_a(ctx->gpr[10], ctx->gpr[9]);
        spu_ls_write128(ctx, ctx->gpr[23]._u32[0] + ctx->gpr[12]._u32[0], ctx->gpr[35]);
        spu_ls_write128(ctx, ctx->gpr[27]._u32[0] + ctx->gpr[12]._u32[0], ctx->gpr[36]);
        ctx->gpr[37] = spu_selb(ctx->gpr[15], ctx->gpr[0], ctx->gpr[37]);
        ctx->gpr[12] = spu_a(ctx->gpr[12], ctx->gpr[14]);
        ctx->gpr[14] = spu_ai(ctx->gpr[9], 0);
        ctx->pc = ctx->gpr[37]._u32[0]; g_spu_trampoline_fn = spu_indirect_branch; return;
        /* nop */;
        /* nop */;
        /* nop */;
        /* nop */;
        /* nop */;
        { ctx->pc = 0xC0; g_spu_trampoline_fn = spu_func_000000C0; return; }
}

void spu_func_000000C0(spu_context* ctx) {
        ctx->stop_code = 0x0u; ctx->status = SPU_STATUS_STOPPED_BY_STOP; spu_stop(ctx); return;
}

/* Function table */
typedef struct { uint32_t addr; void (*func)(spu_context*); const char* name; } spu_func_entry;
static const spu_func_entry spu_function_table[] = {
    { 0x00000000u, spu_func_00000000, "spu_func_00000000" },
    { 0x00000080u, spu_func_00000080, "spu_func_00000080" },
    { 0x000000C0u, spu_func_000000C0, "spu_func_000000C0" },
    { 0, NULL, NULL }
};

void spu_recomp_register(void) {
    for (const spu_func_entry* e = spu_function_table; e->func; ++e)
        spu_register_function(e->addr, e->func);
}
