/* Auto-generated by spu_lifter.py -- do not edit by hand. */
#include "spu_recomp.h"
#include "../../runtime/spu/spu_helpers.h"


void spu_func_00000000(spu_context* ctx) {
        ctx->gpr[3] = spu_il(42);
        ctx->gpr[0] = spu_splat_u32(0x8); spu_func_00000010(ctx);
        spu_wrch(ctx, SPU_WrOutMbox, ctx->gpr[3]);
        ctx->status = SPU_STATUS_STOPPED_BY_STOP; return;
}

void spu_func_00000010(spu_context* ctx) {
        ctx->gpr[4] = spu_il(100);
        ctx->gpr[3] = spu_a(ctx->gpr[3], ctx->gpr[4]);
        return;
}

/* Function table */
typedef struct { uint32_t addr; void (*func)(spu_context*); const char* name; } spu_func_entry;
static const spu_func_entry spu_function_table[] = {
    { 0x00000000u, spu_func_00000000, "spu_func_00000000" },
    { 0x00000010u, spu_func_00000010, "spu_func_00000010" },
    { 0, NULL, NULL }
};

void spu_recomp_register(void) {
    for (const spu_func_entry* e = spu_function_table; e->func; ++e)
        spu_register_function(e->addr, e->func);
}
