/* Auto-generated by spu_lifter.py -- do not edit by hand. */
#pragma once
#include "../../runtime/spu/spu_context.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Cross-function branch/loop = a guest tail-jump to another lifted function's
 * entry. It MUST reuse the current host frame, not nest one: SPURS task loops
 * iterate via these, so nesting overflows the host stack and silently kills the
 * process. clang's musttail guarantees the tail call (a jump); without it (or on
 * a non-clang compiler) we fall back to call+return, which only stays bounded if
 * the compiler happens to do sibling-call optimization. All lifted SPU functions
 * share the signature `void f(spu_context*)`, so the tail call is always valid. */
#if defined(__clang__)
#  define SPU_TAILCALL(call) __attribute__((musttail)) return call
#else
#  define SPU_TAILCALL(call) do { call; return; } while (0)
#endif

/* Indirect branch dispatch (bi/bisl/bid...): PC has been set to the target
 * local-store address; the runtime resolves it to the matching lifted
 * function and continues execution. Implemented by the SPU program glue. */
void spu_indirect_branch(spu_context* ctx);

/* stop/stopd hook (YDKJ): the runtime inspects the stop code, may deliver a
 * stop-and-signal event to the PPU (SPURS bring-up handshake), and longjmps the
 * host SPU thread back to spu_run_with_halt so the job does not spin past the
 * stop. Complements ctx->status; harmless where the runtime handles status. */
void spu_stop(spu_context* ctx);
/* Lower-level longjmp helper: abort the host SPU thread back to spu_run_with_halt
 * (used for the infinite no-op self-loop / idle halt idiom). */
void spu_halt(spu_context* ctx);

/* Channel access -- implemented by the runtime (MFC DMA engine, mailboxes,
 * signal notification, decrementer). See runtime/spu/spu_dma.h. */
u128 spu_rdch(spu_context* ctx, uint32_t channel);
uint32_t spu_rchcnt(spu_context* ctx, uint32_t channel);
void spu_wrch(spu_context* ctx, uint32_t channel, u128 value);

/* Execution trace (only emitted when the lifter was invoked with --trace). */
void spu_trace_init(const char* path);
void spu_trace_pc(spu_context* ctx, uint32_t pc);
void spu_trace_rt(spu_context* ctx, uint32_t rt);

#ifdef __cplusplus
}
#endif


void tsp_spu_func_00000A00(spu_context* ctx);
void tsp_spu_func_00000A70(spu_context* ctx);
void tsp_spu_func_00000B60(spu_context* ctx);
void tsp_spu_func_00000C40(spu_context* ctx);
void tsp_spu_func_00000E40(spu_context* ctx);
void tsp_spu_func_00000E60(spu_context* ctx);
void tsp_spu_func_00000FC4(spu_context* ctx);
void tsp_spu_func_00000FCC(spu_context* ctx);
void tsp_spu_func_00000FD8(spu_context* ctx);
void tsp_spu_func_00001024(spu_context* ctx);
void tsp_spu_func_00001034(spu_context* ctx);
void tsp_spu_func_0000103C(spu_context* ctx);
void tsp_spu_func_00001040(spu_context* ctx);
void tsp_spu_func_00001054(spu_context* ctx);
void tsp_spu_func_00001080(spu_context* ctx);
void tsp_spu_func_00001094(spu_context* ctx);
void tsp_spu_func_000010B4(spu_context* ctx);
void tsp_spu_func_000010B8(spu_context* ctx);
void tsp_spu_func_000010C0(spu_context* ctx);
void tsp_spu_func_000010F0(spu_context* ctx);
void tsp_spu_func_000010F8(spu_context* ctx);
void tsp_spu_func_000011A4(spu_context* ctx);
void tsp_spu_func_000011A8(spu_context* ctx);
void tsp_spu_func_000011E8(spu_context* ctx);
void tsp_spu_func_000011F0(spu_context* ctx);
void tsp_spu_func_000011F4(spu_context* ctx);
void tsp_spu_func_00001244(spu_context* ctx);
void tsp_spu_func_0000128C(spu_context* ctx);
void tsp_spu_func_00001308(spu_context* ctx);
void tsp_spu_func_00001330(spu_context* ctx);
void tsp_spu_func_00001338(spu_context* ctx);
void tsp_spu_func_00001350(spu_context* ctx);
void tsp_spu_func_00001388(spu_context* ctx);
void tsp_spu_func_000013B0(spu_context* ctx);
void tsp_spu_func_00001438(spu_context* ctx);
void tsp_spu_func_000014D0(spu_context* ctx);
void tsp_spu_func_00001620(spu_context* ctx);
void tsp_spu_func_0000172C(spu_context* ctx);
void tsp_spu_func_00001748(spu_context* ctx);
void tsp_spu_func_00001778(spu_context* ctx);
void tsp_spu_func_000018D0(spu_context* ctx);
void tsp_spu_func_000018F0(spu_context* ctx);
void tsp_spu_func_000018F4(spu_context* ctx);
void tsp_spu_func_000018F8(spu_context* ctx);
void tsp_spu_func_000018FC(spu_context* ctx);
void tsp_spu_func_00001900(spu_context* ctx);
void tsp_spu_func_00001904(spu_context* ctx);
void tsp_spu_func_00001908(spu_context* ctx);
void tsp_spu_func_0000190C(spu_context* ctx);
void tsp_spu_func_00001910(spu_context* ctx);
void tsp_spu_func_00001914(spu_context* ctx);
void tsp_spu_func_00001918(spu_context* ctx);
void tsp_spu_func_0000191C(spu_context* ctx);
void tsp_spu_func_00001920(spu_context* ctx);
void tsp_spu_func_00001924(spu_context* ctx);
void tsp_spu_func_00001928(spu_context* ctx);
void tsp_spu_func_0000192C(spu_context* ctx);
void tsp_spu_func_00001930(spu_context* ctx);
void tsp_spu_func_00001934(spu_context* ctx);
void tsp_spu_func_00001954(spu_context* ctx);
void tsp_spu_func_000019B0(spu_context* ctx);
void tsp_spu_func_00001ABC(spu_context* ctx);
void tsp_spu_func_00001B28(spu_context* ctx);
void tsp_spu_func_00001B30(spu_context* ctx);
void tsp_spu_func_00001C04(spu_context* ctx);
void tsp_spu_func_00001C40(spu_context* ctx);
void tsp_spu_func_00001C50(spu_context* ctx);
void tsp_spu_func_00001C58(spu_context* ctx);
void tsp_spu_func_00001C84(spu_context* ctx);
void tsp_spu_func_00001C98(spu_context* ctx);
void tsp_spu_func_00001CD8(spu_context* ctx);
void tsp_spu_func_00001CFC(spu_context* ctx);
void tsp_spu_func_00001D24(spu_context* ctx);
void tsp_spu_func_00001D34(spu_context* ctx);
void tsp_spu_func_00001D80(spu_context* ctx);
void tsp_spu_func_00001DB8(spu_context* ctx);
void tsp_spu_func_00001DFC(spu_context* ctx);
void tsp_spu_func_00001E30(spu_context* ctx);
void tsp_spu_func_00001E40(spu_context* ctx);
void tsp_spu_func_00001E48(spu_context* ctx);
void tsp_spu_func_00001E98(spu_context* ctx);
void tsp_spu_func_00001E9C(spu_context* ctx);
void tsp_spu_func_00001EA4(spu_context* ctx);
void tsp_spu_func_00001EB0(spu_context* ctx);
void tsp_spu_func_00001EC8(spu_context* ctx);
void tsp_spu_func_00001F18(spu_context* ctx);
void tsp_spu_func_00001F68(spu_context* ctx);
void tsp_spu_func_00001F70(spu_context* ctx);
void tsp_spu_func_00001F7C(spu_context* ctx);
void tsp_spu_func_00001FC8(spu_context* ctx);
void tsp_spu_func_00001FE0(spu_context* ctx);
void tsp_spu_func_00001FEC(spu_context* ctx);
void tsp_spu_func_00001FF8(spu_context* ctx);
void tsp_spu_func_00002038(spu_context* ctx);
void tsp_spu_func_0000209C(spu_context* ctx);
void tsp_spu_func_0000211C(spu_context* ctx);
void tsp_spu_func_000021A4(spu_context* ctx);
void tsp_spu_func_00002218(spu_context* ctx);
void tsp_spu_func_00002238(spu_context* ctx);
void tsp_spu_func_0000223C(spu_context* ctx);
void tsp_spu_func_00002240(spu_context* ctx);
void tsp_spu_func_00002244(spu_context* ctx);
void tsp_spu_func_00002248(spu_context* ctx);
void tsp_spu_func_0000224C(spu_context* ctx);
void tsp_spu_func_00002250(spu_context* ctx);
void tsp_spu_func_00002254(spu_context* ctx);
void tsp_spu_func_00002258(spu_context* ctx);
void tsp_spu_func_0000225C(spu_context* ctx);
void tsp_spu_func_00002260(spu_context* ctx);
void tsp_spu_func_00002264(spu_context* ctx);
void tsp_spu_func_00002268(spu_context* ctx);
void tsp_spu_func_0000226C(spu_context* ctx);
void tsp_spu_func_00002270(spu_context* ctx);
void tsp_spu_func_00002274(spu_context* ctx);
void tsp_spu_func_00002278(spu_context* ctx);
void tsp_spu_func_0000227C(spu_context* ctx);
void tsp_spu_func_00002294(spu_context* ctx);
void tsp_spu_func_000022A0(spu_context* ctx);
void tsp_spu_func_000022AC(spu_context* ctx);
void tsp_spu_func_000022B4(spu_context* ctx);
void tsp_spu_func_00002308(spu_context* ctx);
void tsp_spu_func_00002320(spu_context* ctx);
void tsp_spu_func_00002360(spu_context* ctx);
void tsp_spu_func_00002388(spu_context* ctx);
void tsp_spu_func_00002464(spu_context* ctx);
void tsp_spu_func_00002540(spu_context* ctx);
void tsp_spu_func_0000255C(spu_context* ctx);
void tsp_spu_func_000025E0(spu_context* ctx);
void tsp_spu_func_00002780(spu_context* ctx);
void tsp_spu_func_00002820(spu_context* ctx);

/* Runtime glue (runtime/spu/spu_channels.c) */
void spu_register_function(uint32_t addr, void (*fn)(spu_context*));
/* Call once at init to register this image's functions for
 * indirect-branch dispatch (spu_indirect_branch). */
void tsp_spu_recomp_register(void);
