#!/usr/bin/env python3
"""Generate the SPU interpreter's decode tables (C) from the validated Python
decoder (spu_disasm.py). The interpreter is the correctness floor for the SPU
static recompiler: computed/indirect branches (`bi $reg`) and DMA'd or
self-modified code (LBP overlays, spu_0004's `sync; bi $3` trampoline) can't be
statically lifted, so on a lifted-function-table miss we interpret from live
local store. Emitting the opcode->mnemonic tables from spu_disasm keeps the
interpreter's decode bit-identical to the decoder we already proved 100% vs
spu-lv2-objdump; the execute half (spu_interp.c) calls the SAME spu_<mnemonic>
helpers the lifter emits, so lifted and interpreted code share exact semantics.

    python gen_spu_interp.py > ../runtime/spu/spu_interp_tables.inc
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import spu_disasm as D  # RRR_TABLE, RI18_TABLE, RI16_TABLE, RI10_TABLE, SPU_RR, ...

# The RI7 / RI8 / LSX tables live inside spu_decode() as locals; mirror them here
# (kept in sync by this generator; a drift shows immediately in the selftest).
RI7 = {
    0x078: "roti", 0x079: "rotmi", 0x07a: "rotmai", 0x07b: "shli",
    0x07c: "rothi", 0x07d: "rothmi", 0x07e: "rotmahi", 0x07f: "shlhi",
    0x1f4: "cbd", 0x1f5: "chd", 0x1f6: "cwd", 0x1f7: "cdd",
    0x1f8: "rotqbii", 0x1f9: "rotqmbii", 0x1fb: "shlqbii",
    0x1fc: "rotqbyi", 0x1fd: "rotqmbyi", 0x1ff: "shlqbyi",
}
RI7_UNSIGNED = {"cbd", "chd", "cwd", "cdd"}
RI8 = {0x1d8: "cflts", 0x1d9: "cfltu", 0x1da: "csflt", 0x1db: "cuflt"}  # op10
LSX = {0x1c4: "lqx", 0x144: "stqx"}

# Every mnemonic the decoder can emit -> a stable enum. `.word` is the trap.
all_mn = set()
for t in (D.RRR_TABLE, D.RI18_TABLE, D.RI16_TABLE, D.RI10_TABLE, D.SPU_RR,
          RI7, RI8, LSX):
    all_mn.update(t.values())
all_mn.update(["rdch", "wrch", "rchcnt", ".word"])
mnems = sorted(all_mn)


def enum_name(m):
    return "SPU_" + ("word" if m == ".word" else m)


out = []
w = out.append
w("/* GENERATED by tools/gen_spu_interp.py -- do not edit. */")
w("/* Opcode->mnemonic tables for the SPU interpreter, from the validated")
w(" * spu_disasm.py decoder. Regenerate after any decoder table change. */")
w("")
w("typedef enum {")
for m in mnems:
    w(f"    {enum_name(m)},")
w("    SPU_OP_COUNT")
w("} spu_op;")
w("")
w("static const char* const spu_op_name[SPU_OP_COUNT] = {")
for m in mnems:
    w(f'    [{enum_name(m)}] = "{m}",')
w("};")
w("")


def emit_lookup(fn, table, argbits, argname):
    w(f"static spu_op {fn}(uint32_t {argname}) {{")
    w("    switch (%s) {" % argname)
    for k in sorted(table):
        w(f"    case 0x{k:X}: return {enum_name(table[k])};")
    w(f"    default: return SPU_word;")
    w("    }")
    w("}")
    w("")


emit_lookup("spu_dec_rrr", D.RRR_TABLE, 4, "op4")
emit_lookup("spu_dec_ri18", D.RI18_TABLE, 7, "op7")
emit_lookup("spu_dec_ri16", D.RI16_TABLE, 9, "op9")
emit_lookup("spu_dec_ri10", D.RI10_TABLE, 8, "op8")
emit_lookup("spu_dec_ri8", RI8, 10, "op10")
emit_lookup("spu_dec_rr", D.SPU_RR, 11, "op11")
emit_lookup("spu_dec_ri7", RI7, 11, "op11")
emit_lookup("spu_dec_lsx", LSX, 11, "op11")

w("/* signed-vs-unsigned i7 per instruction (Table 2-6) */")
w("static int spu_ri7_unsigned(spu_op op) {")
w("    return %s;" % " || ".join(f"op == {enum_name(m)}" for m in sorted(RI7_UNSIGNED)))
w("}")

sys.stdout.write("\n".join(out) + "\n")
