import os, re, collections
NL = chr(10)
ROOTS = ['runtime', 'libs', 'tools']
PAT = re.compile(r'getenv\(\s*"([A-Za-z_][A-Za-z_0-9]*)"\s*\)')
COMMENT = re.compile(r'^\s*(?:/\*|\*|//)\s?(.*)$')

hits = collections.defaultdict(list)   # name -> [(file, line, desc)]
for root in ROOTS:
    for dp, _dn, fn in os.walk(root):
        if '.git' in dp: continue
        for f in fn:
            if not f.endswith(('.c', '.cpp', '.h', '.hpp', '.m', '.py')): continue
            p = os.path.join(dp, f)
            try: lines = open(p, encoding='utf-8', errors='replace').read().split(NL)
            except Exception: continue
            for i, l in enumerate(lines):
                for m in PAT.finditer(l):
                    name = m.group(1)
                    # nearest preceding comment block, up to 6 lines back
                    desc = ''
                    for j in range(i - 1, max(-1, i - 7), -1):
                        c = COMMENT.match(lines[j])
                        if c:
                            t = c.group(1).strip()
                            if t and not t.startswith('---'):
                                desc = t if not desc else t + ' ' + desc
                        elif desc:
                            break
                        elif lines[j].strip():
                            break
                    # a same-line trailing comment wins
                    tc = re.search(r'/\*\s*(.*?)\s*\*/|//\s*(.*)$', l)
                    if tc and (tc.group(1) or tc.group(2)):
                        desc = (tc.group(1) or tc.group(2)).strip()
                    hits[name].append((p.replace(os.sep, '/'), i + 1, desc))

groups = collections.defaultdict(list)
for name, locs in hits.items():
    pre = name.split('_')[0]
    groups[pre].append((name, locs))

out = []
out.append('# Runtime diagnostics')
out.append('')
out.append('> Generated by `tools/gen_diagnostics_index.py`. Do not edit by hand.')
out.append('')
out.append('Every environment variable the runtime reads, with where it is read and')
out.append('whatever the source says about it. **%d knobs across %d groups.**'
           % (len(hits), len(groups)))
out.append('')
out.append('Most are read once, at first use, and cached — so they are set before launch,')
out.append('not changed while a title runs.')
out.append('')
out.append('| group | knobs |')
out.append('|---|---|')
for pre in sorted(groups, key=lambda k: -len(groups[k])):
    out.append('| `%s_*` | %d |' % (pre, len(groups[pre])))
out.append('')
for pre in sorted(groups):
    out.append('## `%s`' % pre)
    out.append('')
    for name, locs in sorted(groups[pre]):
        f, ln, desc = locs[0]
        extra = '' if len(locs) == 1 else '  _(+%d more sites)_' % (len(locs) - 1)
        out.append('- **`%s`** — %s' % (name, desc if desc else '_(no description in source)_'))
        out.append('  `%s:%d`%s' % (f, ln, extra))
    out.append('')

os.makedirs('docs', exist_ok=True)
open('docs/DIAGNOSTICS.md', 'w', encoding='utf-8').write(NL.join(out) + NL)
print('wrote docs/DIAGNOSTICS.md:', len(hits), 'knobs,', len(groups), 'groups')
described = sum(1 for n in hits if hits[n][0][2])
print('with a description from source:', described, '(%d%%)' % (100*described//len(hits)))
