#!/usr/bin/env python3
"""
Write the registration unit for a lifted firmware (or title) PRX module, so
lv2's PRX loader (runtime/syscalls/lv2_prx.c) can load it by file name.

Inputs are the two halves of the pipeline in docs/FIRMWARE_LLE.md:
  - tools/lift_prx.py's output directory (<stem>_image.bin, <stem>_exports.json)
  - the --symbol-prefix that tools/ppu_lifter.py was run with, which names the
    lifted function table (<prefix>function_table)

The generated C++ file embeds the relocated image, lists the module's exports
(NID -> OPD, base-relative) and its module_start / module_stop, and registers
all of it with prx_static_register() from a static initializer.

The output is derived from firmware: like the image and the lifted C, it
belongs in a local build directory, never in the repository.

usage: gen_prx_module.py LIFT_DIR --stem libsre --file libsre.sprx
                         --prefix libsre_ --out libsre_module.cpp
"""
import argparse
import json
import os

NID_MODULE_START = 0xBC9A0086
NID_MODULE_STOP = 0xAB779874


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("lift_dir")
    ap.add_argument("--stem", required=True, help="lift_prx output stem (file prefix)")
    ap.add_argument("--file", required=True, help="file name the guest loads it by")
    ap.add_argument("--prefix", required=True, help="ppu_lifter --symbol-prefix")
    ap.add_argument("--out", required=True)
    a = ap.parse_args()

    img = open(os.path.join(a.lift_dir, a.stem + "_image.bin"), "rb").read()
    meta = json.load(open(os.path.join(a.lift_dir, a.stem + "_exports.json")))
    base = int(meta["base"], 16)

    exports, start, stop = [], 0, 0
    for lib, entries in meta["exports"].items():
        for nid_s, opd_s in entries.items():
            nid, opd = int(nid_s, 16), int(opd_s, 16)
            if lib == "!syslib":
                if nid == NID_MODULE_START:
                    start = opd
                elif nid == NID_MODULE_STOP:
                    stop = opd
                continue
            exports.append((nid, opd - base, lib))

    sym = a.prefix + "prx"
    out = []
    w = out.append
    w("/* Generated by tools/gen_prx_module.py from a firmware module: local")
    w(" * build output, not for the repository. */")
    w('#include "prx_loader.h"')
    w("")
    w('extern "C" {')
    w("extern const prx_func_entry %sfunction_table[];" % a.prefix)
    w("extern const uint64_t %sfunction_table_count;" % a.prefix)
    w("}")
    w("")
    w("static const unsigned char %s_image[%d] = {" % (sym, len(img)))
    for i in range(0, len(img), 24):
        w("  " + ",".join(str(b) for b in img[i:i + 24]) + ",")
    w("};")
    w("")
    w("static const prx_export %s_exports[%d] = {" % (sym, len(exports)))
    for nid, va, lib in exports:
        w("  { 0x%08Xu, 0x%08Xu },  /* %s */" % (nid, va, lib))
    w("};")
    w("")
    w("static prx_static_module %s_module;" % sym)
    w("")
    w("namespace {")
    w("struct %s_reg {" % sym)
    w("  %s_reg() {" % sym)
    w("    prx_static_module& m = %s_module;" % sym)
    w('    m.file = "%s";' % a.file)
    w('    m.mod.name = "%s";' % meta["module"])
    w("    m.mod.base = 0x%08Xu;" % base)
    w("    m.mod.image = %s_image;" % sym)
    w("    m.mod.image_size = %du;" % len(img))
    w("    m.mod.funcs = %sfunction_table;" % a.prefix)
    w("    m.mod.func_count = %sfunction_table_count;" % a.prefix)
    w("    m.mod.exports = %s_exports;" % sym)
    w("    m.mod.export_count = %du;" % len(exports))
    w("    m.start_opd = 0x%08Xu;" % start)
    w("    m.stop_opd = 0x%08Xu;" % stop)
    w('    m.module_name = "%s";' % meta["module"])
    w("    prx_static_register(&m);")
    w("  }")
    w("} %s_reg_instance;" % sym)
    w("}")
    open(a.out, "w").write("\n".join(out) + "\n")
    print("%s: %s, %d bytes at 0x%08X, %d exports, start 0x%08X stop 0x%08X"
          % (a.out, a.file, len(img), base, len(exports), start, stop))


if __name__ == "__main__":
    main()
