#!/usr/bin/env python3
"""
Batch-lift the extracted WWS SPU job modules to C.

Each module is DMA'd into the SPU job code buffer at LS 0x4000 and entered at
0x4000 + entryOffset. Because only one module is resident in the code buffer at
a time (the FMOD-overlay model), every module lifts at the SAME base (0x4000);
the runtime picks the resident one by content signature.

For each module:
  1. wrap the raw bytes as a minimal SPU ELF (base 0x4000, entry 0x4000+entryOff)
  2. run spu_lifter --auto-functions, which uses find_spu_functions.detect_functions
     to seed from entry + branch/call/jump-table targets -- so rodata past the
     last function is never disassembled (no .word data-as-code).
  3. unique --symbol-prefix per module so all 89 link together.

Output: lbp_spu/lifted/<modname>/spu_recomp.{c,h}
Also writes lbp_spu/lifted/jobmods_manifest.json: [{name, prefix, base, entry,
sig(hex16), size, funcs, unsupported}].
"""
import glob, hashlib, json, os, struct, subprocess, sys
sys.path.insert(0, os.path.dirname(__file__))
from wrap_spu_elf import wrap

ROOT   = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
JOBMODS= os.path.join(ROOT, "lbp_spu", "jobmods")
OUTDIR = os.path.join(ROOT, "lbp_spu", "lifted")
LIFTER = os.path.join(os.path.dirname(__file__), "spu_lifter.py")
BASE   = 0x4000

def main():
    mods = sorted(glob.glob(os.path.join(JOBMODS, "*.bin")))
    os.makedirs(OUTDIR, exist_ok=True)
    manifest = []
    tmp_elf = os.path.join(OUTDIR, "_tmp.elf")
    for path in mods:
        raw = open(path, "rb").read()
        name = os.path.splitext(os.path.basename(path))[0]         # jobmod_<sha>_e<entry>
        sha  = name.split("_")[1]
        entry_off = struct.unpack_from(">I", raw, 0x10)[0]
        entry = BASE + entry_off
        prefix = f"{name}_"
        outsub = os.path.join(OUTDIR, name)
        # content signature: first 16 bytes (the 4 ila header uniquely identify a module)
        sig = raw[:16]

        elf = wrap(raw, base=BASE, entry=entry)
        with open(tmp_elf, "wb") as f:
            f.write(elf)

        r = subprocess.run(
            [sys.executable, LIFTER, "--auto-functions", tmp_elf, "--base", hex(BASE),
             "--symbol-prefix", prefix, "-o", outsub,
             "--source-name", "spu_recomp.c", "--header-name", "spu_recomp.h"],
            capture_output=True, text=True)
        if r.returncode != 0:
            print(f"  FAIL {name}\n{r.stderr}", file=sys.stderr)
            continue
        # parse stats from lifter stdout
        funcs = unsup = 0
        for line in r.stdout.splitlines():
            s = line.strip()
            if s.endswith("function(s) lifted"):
                funcs = int(s.split()[0])
            if "unsupported instruction(s)" in s:
                unsup = int(s.split()[0])
        manifest.append({
            "name": name, "prefix": prefix, "base": BASE, "entry": entry,
            "entry_off": entry_off, "sig": sig.hex(), "size": len(raw),
            "funcs": funcs, "unsupported": unsup,
        })
        flag = "  <-- UNSUPPORTED" if unsup else ""
        print(f"  {name:40} funcs={funcs:3} unsup={unsup:3} entry=0x{entry:X}{flag}")

    if os.path.exists(tmp_elf):
        os.remove(tmp_elf)
    with open(os.path.join(OUTDIR, "jobmods_manifest.json"), "w") as f:
        json.dump(manifest, f, indent=2)
    emit_register(manifest)
    tot_unsup = sum(m["unsupported"] for m in manifest)
    print(f"\nLifted {len(manifest)} module(s), {tot_unsup} total unsupported instruction(s)")
    print(f"Manifest: {os.path.join(OUTDIR, 'jobmods_manifest.json')}")

# Image ids for the job-code overlays. Well clear of the fingerprint-dispatched
# images (1..25), the FMOD overlays (60..65) and the taskset policy (100).
JOBMOD_IMAGE_BASE = 200
REGISTER_C = os.path.join(ROOT, "lbp", "gen", "jobmods_register.c")

def emit_register(manifest):
    """Generate lbp/gen/jobmods_register.c: register every job module's lifted
    functions under a distinct image id, plus its 16-byte content signature so
    spu_overlay_note_get flips resident_ovl when the module DMAs into the job
    code buffer (LS 0x4000). Dispatched exactly like the FMOD codec overlays."""
    L = []
    L.append("/* jobmods_register.c -- GENERATED by tools/lift_jobmods.py.")
    L.append(" * WWS SPU job-code modules extracted from patch.sdat/data.sdat. Every module")
    L.append(" * streams into the same job code buffer (LS 0x4000) and is entered at")
    L.append(" * 0x4000+entryOffset; only one is resident at a time, so each registers its")
    L.append(" * lifted functions under a distinct image id and a 16-byte content signature.")
    L.append(" * spu_overlay_note_get() sets spu_context.resident_ovl on the DMA that copies")
    L.append(" * the module in; dispatch then resolves 0x4000+ pcs against that overlay. */")
    L.append("#include <stdint.h>")
    L.append("")
    L.append("extern void spu_begin_image(int image_id);")
    L.append("extern void spu_overlay_register_sig(const uint8_t sig[16], int image_id);")
    L.append("")
    for m in manifest:
        L.append(f"extern void {m['prefix']}spu_recomp_register(void);")
    L.append("")
    L.append("void lbp_jobmods_register_all(void)")
    L.append("{")
    for i, m in enumerate(manifest):
        img = JOBMOD_IMAGE_BASE + i
        sig = bytes.fromhex(m["sig"])
        arr = ",".join(f"0x{b:02X}" for b in sig)
        L.append(f"    {{ static const uint8_t sig[16] = {{{arr}}};")
        L.append(f"      spu_begin_image({img}); {m['prefix']}spu_recomp_register();")
        L.append(f"      spu_overlay_register_sig(sig, {img}); }}   /* {m['name']} entry 0x{m['entry']:X} */")
    L.append("    spu_begin_image(0);")
    L.append("}")
    L.append("")
    L.append("__attribute__((constructor)) static void lbp_jobmods_register_ctor(void)")
    L.append("{")
    L.append("    lbp_jobmods_register_all();")
    L.append("}")
    L.append("")
    os.makedirs(os.path.dirname(REGISTER_C), exist_ok=True)
    with open(REGISTER_C, "w") as f:
        f.write("\n".join(L))
    print(f"Wrote {REGISTER_C} ({len(manifest)} modules, image ids "
          f"{JOBMOD_IMAGE_BASE}..{JOBMOD_IMAGE_BASE + len(manifest) - 1})")

if __name__ == "__main__":
    main()
