#!/usr/bin/env python3
"""
PPU instruction lifter -- translates PowerPC 64 disassembly into C code
for use with a recompilation runtime.

Each original function is emitted as a C function taking a ``ppu_context*``
parameter.  Instructions are translated into equivalent C statements that
manipulate the context struct (GPRs, FPRs, CR, LR, CTR, memory helpers).

Usage:
    python ppu_lifter.py <input_elf_or_bin> [--output dir] [--header] [--functions FILE]
"""

import argparse
import json
import os
import re
import sys
from dataclasses import dataclass, field

# ---------------------------------------------------------------------------
# We import the disassembler from the same directory.
# ---------------------------------------------------------------------------
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

try:
    from ppu_disasm import (Instruction, disassemble_bytes, detect_functions,
                            decode, sign_extend, bits, bit)
except ImportError:
    print("Error: ppu_disasm.py must be in the same directory.", file=sys.stderr)
    sys.exit(1)

# ---------------------------------------------------------------------------
# Lifter context
# ---------------------------------------------------------------------------

HEADER_PREAMBLE = """\
/* Auto-generated by ppu_lifter.py -- do not edit by hand. */
#pragma once
#include <stdint.h>

typedef struct ppu_context {
    uint64_t gpr[32];   /* General-purpose registers */
    double   fpr[32];   /* Floating-point registers  */
    uint32_t cr;        /* Condition register         */
    uint64_t lr;        /* Link register              */
    uint64_t ctr;       /* Count register             */
    uint64_t xer;       /* Fixed-point exception reg  */
    uint64_t pc;        /* Program counter            */
} ppu_context;

/* Memory access helpers (provided by runtime) */
uint8_t  vm_read8 (uint64_t addr);
uint16_t vm_read16(uint64_t addr);
uint32_t vm_read32(uint64_t addr);
uint64_t vm_read64(uint64_t addr);
void     vm_write8 (uint64_t addr, uint8_t  val);
void     vm_write16(uint64_t addr, uint16_t val);
void     vm_write32(uint64_t addr, uint32_t val);
void     vm_write64(uint64_t addr, uint64_t val);

/* Syscall handler */
void lv2_syscall(ppu_context* ctx);

"""

SOURCE_PREAMBLE = """\
/* Auto-generated by ppu_lifter.py -- do not edit by hand. */
#include "ppu_recomp.h"
#include <stdio.h>

"""

# ---------------------------------------------------------------------------
# Instruction -> C translation
# ---------------------------------------------------------------------------

def _parse_operands(operands: str) -> list[str]:
    """Split operands string by commas, stripping whitespace."""
    return [o.strip() for o in operands.split(",") if o.strip()]


def _reg_idx(token: str) -> str:
    """Extract register index from 'r3' -> '3', 'f5' -> '5', 'v2' -> '2'."""
    m = re.match(r"[rfv](\d+)", token)
    return m.group(1) if m else token


def _disp_base(token: str):
    """Parse 'disp(rN)' -> (disp_str, N)."""
    m = re.match(r"(-?0x[0-9A-Fa-f]+|[0-9-]+)\(r(\d+)\)", token)
    if m:
        disp = m.group(1)
        base = m.group(2)
        return disp, base
    return None, None


def _imm(token: str) -> str:
    """Return a C literal for an immediate value token."""
    token = token.strip()
    if token.startswith("0x") or token.startswith("-0x"):
        return token
    try:
        v = int(token)
        if v < 0:
            return str(v)
        return f"0x{v:X}" if v > 9 else str(v)
    except ValueError:
        return token


def _cr_field_set(bf: int) -> str:
    """Generate C to set a CR field from a comparison result."""
    shift = (7 - bf) * 4
    return (f"ctx->cr = (ctx->cr & ~(0xFu << {shift})) | "
            f"(cr_val << {shift})")


@dataclass
class LiftedFunction:
    """A single lifted C function."""
    name: str = ""
    start_addr: int = 0
    end_addr: int = 0
    body_lines: list[str] = field(default_factory=list)
    calls: list[int] = field(default_factory=list)  # addresses of bl targets


class PPULifter:
    """Translates PPU instructions into C source."""

    def __init__(self):
        self.functions: list[LiftedFunction] = []
        self.call_targets: set[int] = set()

    def lift_function(self, instructions: list[Instruction],
                      start: int, end: int) -> LiftedFunction:
        """Lift a range of instructions into a C function."""
        func = LiftedFunction(
            name=f"func_{start:08X}",
            start_addr=start,
            end_addr=end,
        )

        # Collect branch targets within the function for labels
        internal_targets: set[int] = set()
        for insn in instructions:
            if insn.addr < start or insn.addr >= end:
                continue
            if insn.mnemonic.startswith("b") and insn.mnemonic not in (
                    "blr", "bctr", "bctrl", "bl", "blrl"):
                ops = _parse_operands(insn.operands)
                for op in ops:
                    if op.startswith("0x"):
                        try:
                            target = int(op, 16)
                            if start <= target < end:
                                internal_targets.add(target)
                        except ValueError:
                            pass

        for insn in instructions:
            if insn.addr < start or insn.addr >= end:
                continue

            # Label
            if insn.addr in internal_targets:
                func.body_lines.append(f"loc_{insn.addr:08X}:")

            c_line = self._translate(insn, func)
            if c_line:
                func.body_lines.append(f"    {c_line}")

        self.functions.append(func)
        return func

    # ------------------------------------------------------------------ #
    # Per-instruction translation
    # ------------------------------------------------------------------ #

    def _translate(self, insn: Instruction, func: LiftedFunction) -> str:
        """Translate one Instruction to a C statement string."""
        mn = insn.mnemonic
        ops = _parse_operands(insn.operands)
        addr = insn.addr

        # ------- Arithmetic -------
        if mn == "li":
            rd = _reg_idx(ops[0])
            return f"ctx->gpr[{rd}] = (int64_t)(int32_t)({_imm(ops[1])});"

        if mn == "lis":
            rd = _reg_idx(ops[0])
            return f"ctx->gpr[{rd}] = (int64_t)(int32_t)((uint32_t){_imm(ops[1])} << 16);"

        if mn == "addi":
            rd, ra = _reg_idx(ops[0]), _reg_idx(ops[1])
            return f"ctx->gpr[{rd}] = (int64_t)(int32_t)(ctx->gpr[{ra}] + {_imm(ops[2])});"

        if mn == "addis":
            rd, ra = _reg_idx(ops[0]), _reg_idx(ops[1])
            return f"ctx->gpr[{rd}] = (int64_t)(int32_t)(ctx->gpr[{ra}] + ((uint32_t){_imm(ops[2])} << 16));"

        if mn == "addic" or mn == "addic.":
            rd, ra = _reg_idx(ops[0]), _reg_idx(ops[1])
            return f"ctx->gpr[{rd}] = (int64_t)(int32_t)(ctx->gpr[{ra}] + {_imm(ops[2])});"

        if mn in ("add", "add.", "addo", "addo."):
            rd, ra, rb = _reg_idx(ops[0]), _reg_idx(ops[1]), _reg_idx(ops[2])
            return f"ctx->gpr[{rd}] = (int64_t)(int32_t)((uint32_t)ctx->gpr[{ra}] + (uint32_t)ctx->gpr[{rb}]);"

        if mn in ("subf", "subf.", "subfo"):
            rd, ra, rb = _reg_idx(ops[0]), _reg_idx(ops[1]), _reg_idx(ops[2])
            return f"ctx->gpr[{rd}] = (int64_t)(int32_t)((uint32_t)ctx->gpr[{rb}] - (uint32_t)ctx->gpr[{ra}]);"

        if mn == "subfic":
            rd, ra = _reg_idx(ops[0]), _reg_idx(ops[1])
            return f"ctx->gpr[{rd}] = (int64_t)(int32_t)({_imm(ops[2])} - (int32_t)ctx->gpr[{ra}]);"

        if mn in ("neg", "neg."):
            rd, ra = _reg_idx(ops[0]), _reg_idx(ops[1])
            return f"ctx->gpr[{rd}] = (int64_t)(int32_t)(-(int32_t)ctx->gpr[{ra}]);"

        if mn == "mulli":
            rd, ra = _reg_idx(ops[0]), _reg_idx(ops[1])
            return f"ctx->gpr[{rd}] = (int64_t)(int32_t)((int32_t)ctx->gpr[{ra}] * {_imm(ops[2])});"

        if mn in ("mullw", "mullw."):
            rd, ra, rb = _reg_idx(ops[0]), _reg_idx(ops[1]), _reg_idx(ops[2])
            return f"ctx->gpr[{rd}] = (int64_t)(int32_t)((int32_t)ctx->gpr[{ra}] * (int32_t)ctx->gpr[{rb}]);"

        if mn in ("mulhw", "mulhw."):
            rd, ra, rb = _reg_idx(ops[0]), _reg_idx(ops[1]), _reg_idx(ops[2])
            return f"ctx->gpr[{rd}] = (int64_t)(int32_t)((int32_t)((int64_t)(int32_t)ctx->gpr[{ra}] * (int64_t)(int32_t)ctx->gpr[{rb}] >> 32));"

        if mn in ("mulhwu", "mulhwu."):
            rd, ra, rb = _reg_idx(ops[0]), _reg_idx(ops[1]), _reg_idx(ops[2])
            return f"ctx->gpr[{rd}] = (int64_t)(int32_t)((int32_t)((uint64_t)(uint32_t)ctx->gpr[{ra}] * (uint64_t)(uint32_t)ctx->gpr[{rb}] >> 32));"

        if mn in ("divw", "divw."):
            rd, ra, rb = _reg_idx(ops[0]), _reg_idx(ops[1]), _reg_idx(ops[2])
            return f"ctx->gpr[{rd}] = (int64_t)(int32_t)((int32_t)ctx->gpr[{ra}] / (int32_t)ctx->gpr[{rb}]);"

        if mn in ("divwu", "divwu."):
            rd, ra, rb = _reg_idx(ops[0]), _reg_idx(ops[1]), _reg_idx(ops[2])
            return f"ctx->gpr[{rd}] = (int64_t)(int32_t)((uint32_t)ctx->gpr[{ra}] / (uint32_t)ctx->gpr[{rb}]);"

        # ------- Logical -------
        if mn == "ori":
            ra, rs = _reg_idx(ops[0]), _reg_idx(ops[1])
            return f"ctx->gpr[{ra}] = ctx->gpr[{rs}] | {_imm(ops[2])};"

        if mn == "oris":
            ra, rs = _reg_idx(ops[0]), _reg_idx(ops[1])
            return f"ctx->gpr[{ra}] = ctx->gpr[{rs}] | ((uint64_t){_imm(ops[2])} << 16);"

        if mn == "xori":
            ra, rs = _reg_idx(ops[0]), _reg_idx(ops[1])
            return f"ctx->gpr[{ra}] = ctx->gpr[{rs}] ^ {_imm(ops[2])};"

        if mn == "xoris":
            ra, rs = _reg_idx(ops[0]), _reg_idx(ops[1])
            return f"ctx->gpr[{ra}] = ctx->gpr[{rs}] ^ ((uint64_t){_imm(ops[2])} << 16);"

        if mn in ("andi.", "andis."):
            ra, rs = _reg_idx(ops[0]), _reg_idx(ops[1])
            shift = " << 16" if mn == "andis." else ""
            return f"ctx->gpr[{ra}] = ctx->gpr[{rs}] & ((uint64_t){_imm(ops[2])}{shift});"

        if mn == "nop":
            return "/* nop */;"

        for log_mn, c_op in [("and", "&"), ("or", "|"), ("xor", "^")]:
            if mn == log_mn or mn == log_mn + ".":
                ra, rs, rb = _reg_idx(ops[0]), _reg_idx(ops[1]), _reg_idx(ops[2])
                return f"ctx->gpr[{ra}] = ctx->gpr[{rs}] {c_op} ctx->gpr[{rb}];"

        if mn in ("nand", "nand."):
            ra, rs, rb = _reg_idx(ops[0]), _reg_idx(ops[1]), _reg_idx(ops[2])
            return f"ctx->gpr[{ra}] = ~(ctx->gpr[{rs}] & ctx->gpr[{rb}]);"

        if mn in ("nor", "nor."):
            ra, rs, rb = _reg_idx(ops[0]), _reg_idx(ops[1]), _reg_idx(ops[2])
            return f"ctx->gpr[{ra}] = ~(ctx->gpr[{rs}] | ctx->gpr[{rb}]);"

        if mn in ("andc", "andc."):
            ra, rs, rb = _reg_idx(ops[0]), _reg_idx(ops[1]), _reg_idx(ops[2])
            return f"ctx->gpr[{ra}] = ctx->gpr[{rs}] & ~ctx->gpr[{rb}];"

        if mn in ("orc", "orc."):
            ra, rs, rb = _reg_idx(ops[0]), _reg_idx(ops[1]), _reg_idx(ops[2])
            return f"ctx->gpr[{ra}] = ctx->gpr[{rs}] | ~ctx->gpr[{rb}];"

        if mn in ("extsb", "extsb."):
            ra, rs = _reg_idx(ops[0]), _reg_idx(ops[1])
            return f"ctx->gpr[{ra}] = (int64_t)(int8_t)ctx->gpr[{rs}];"

        if mn in ("extsh", "extsh."):
            ra, rs = _reg_idx(ops[0]), _reg_idx(ops[1])
            return f"ctx->gpr[{ra}] = (int64_t)(int16_t)ctx->gpr[{rs}];"

        if mn in ("extsw", "extsw."):
            ra, rs = _reg_idx(ops[0]), _reg_idx(ops[1])
            return f"ctx->gpr[{ra}] = (int64_t)(int32_t)ctx->gpr[{rs}];"

        if mn in ("cntlzw", "cntlzw."):
            ra, rs = _reg_idx(ops[0]), _reg_idx(ops[1])
            return f"ctx->gpr[{ra}] = __builtin_clz((uint32_t)ctx->gpr[{rs}]);"

        # ------- Shift / Rotate -------
        if mn.startswith("rlwinm"):
            ra, rs = _reg_idx(ops[0]), _reg_idx(ops[1])
            sh, mb, me = ops[2], ops[3], ops[4]
            return (f"ctx->gpr[{ra}] = (int64_t)(int32_t)"
                    f"ppc_rlwinm((uint32_t)ctx->gpr[{rs}], {sh}, {mb}, {me});")

        if mn.startswith("rlwimi"):
            ra, rs = _reg_idx(ops[0]), _reg_idx(ops[1])
            sh, mb, me = ops[2], ops[3], ops[4]
            return (f"ctx->gpr[{ra}] = (int64_t)(int32_t)"
                    f"ppc_rlwimi((uint32_t)ctx->gpr[{ra}], (uint32_t)ctx->gpr[{rs}], {sh}, {mb}, {me});")

        if mn in ("slw", "slw."):
            ra, rs, rb = _reg_idx(ops[0]), _reg_idx(ops[1]), _reg_idx(ops[2])
            return f"ctx->gpr[{ra}] = (int64_t)(int32_t)((uint32_t)ctx->gpr[{rs}] << (ctx->gpr[{rb}] & 0x3F));"

        if mn in ("srw", "srw."):
            ra, rs, rb = _reg_idx(ops[0]), _reg_idx(ops[1]), _reg_idx(ops[2])
            return f"ctx->gpr[{ra}] = (int64_t)(int32_t)((uint32_t)ctx->gpr[{rs}] >> (ctx->gpr[{rb}] & 0x3F));"

        if mn in ("sraw", "sraw."):
            ra, rs, rb = _reg_idx(ops[0]), _reg_idx(ops[1]), _reg_idx(ops[2])
            return f"ctx->gpr[{ra}] = (int64_t)(int32_t)((int32_t)ctx->gpr[{rs}] >> (ctx->gpr[{rb}] & 0x3F));"

        if mn in ("srawi", "srawi."):
            ra, rs = _reg_idx(ops[0]), _reg_idx(ops[1])
            return f"ctx->gpr[{ra}] = (int64_t)(int32_t)((int32_t)ctx->gpr[{rs}] >> {_imm(ops[2])});"

        # ------- 64-bit Rotate / Shift -------
        if mn.startswith("rldicl"):
            # rldicl rA, rS, sh, mb  -- rotate left dword then clear left
            ra, rs = _reg_idx(ops[0]), _reg_idx(ops[1])
            sh, mb = int(ops[2]), int(ops[3])
            return (f"ctx->gpr[{ra}] = ppc_rldicl(ctx->gpr[{rs}], {sh}, {mb});")

        if mn.startswith("rldicr"):
            # rldicr rA, rS, sh, me  -- rotate left dword then clear right
            ra, rs = _reg_idx(ops[0]), _reg_idx(ops[1])
            sh, me = int(ops[2]), int(ops[3])
            return (f"ctx->gpr[{ra}] = ppc_rldicr(ctx->gpr[{rs}], {sh}, {me});")

        if mn.startswith("rldic") and not mn.startswith("rldicl") and not mn.startswith("rldicr"):
            # rldic rA, rS, sh, mb
            ra, rs = _reg_idx(ops[0]), _reg_idx(ops[1])
            sh, mb = int(ops[2]), int(ops[3])
            return (f"ctx->gpr[{ra}] = ppc_rldic(ctx->gpr[{rs}], {sh}, {mb});")

        if mn.startswith("rldimi"):
            # rldimi rA, rS, sh, mb  -- rotate left dword then insert mask
            ra, rs = _reg_idx(ops[0]), _reg_idx(ops[1])
            sh, mb = int(ops[2]), int(ops[3])
            return (f"ctx->gpr[{ra}] = ppc_rldimi(ctx->gpr[{ra}], ctx->gpr[{rs}], {sh}, {mb});")

        # 64-bit shifts
        if mn in ("sld", "sld."):
            ra, rs, rb = _reg_idx(ops[0]), _reg_idx(ops[1]), _reg_idx(ops[2])
            return f"ctx->gpr[{ra}] = (ctx->gpr[{rb}] & 64) ? 0 : (ctx->gpr[{rs}] << (ctx->gpr[{rb}] & 63));"

        if mn in ("srd", "srd."):
            ra, rs, rb = _reg_idx(ops[0]), _reg_idx(ops[1]), _reg_idx(ops[2])
            return f"ctx->gpr[{ra}] = (ctx->gpr[{rb}] & 64) ? 0 : (ctx->gpr[{rs}] >> (ctx->gpr[{rb}] & 63));"

        if mn in ("srad", "srad."):
            ra, rs, rb = _reg_idx(ops[0]), _reg_idx(ops[1]), _reg_idx(ops[2])
            return f"ctx->gpr[{ra}] = (uint64_t)((int64_t)ctx->gpr[{rs}] >> (ctx->gpr[{rb}] & 63));"

        if mn in ("sradi", "sradi."):
            ra, rs = _reg_idx(ops[0]), _reg_idx(ops[1])
            return f"ctx->gpr[{ra}] = (uint64_t)((int64_t)ctx->gpr[{rs}] >> {_imm(ops[2])});"

        # ------- Loads -------
        load_map = {
            "lbz": ("vm_read8", False), "lbzu": ("vm_read8", False),
            "lhz": ("vm_read16", False), "lhzu": ("vm_read16", False),
            "lha": ("vm_read16", True), "lhau": ("vm_read16", True),
            "lwz": ("vm_read32", False), "lwzu": ("vm_read32", False),
            "ld": ("vm_read64", False), "ldu": ("vm_read64", False),
        }
        if mn in load_map:
            helper, signed = load_map[mn]
            rd_i = _reg_idx(ops[0])
            disp, base = _disp_base(ops[1])
            if disp is not None:
                expr = f"{helper}(ctx->gpr[{base}] + {disp})"
                if signed and "16" in helper:
                    expr = f"(int64_t)(int16_t){expr}"
                return f"ctx->gpr[{rd_i}] = {expr};"
            return f"/* {mn} unhandled operands: {insn.operands} */;"

        # ------- Stores -------
        store_map = {
            "stb": "vm_write8", "stbu": "vm_write8",
            "sth": "vm_write16", "sthu": "vm_write16",
            "stw": "vm_write32", "stwu": "vm_write32",
            "std": "vm_write64", "stdu": "vm_write64",
        }
        if mn in store_map:
            helper = store_map[mn]
            rs_i = _reg_idx(ops[0])
            disp, base = _disp_base(ops[1])
            if disp is not None:
                line = f"{helper}(ctx->gpr[{base}] + {disp}, ctx->gpr[{rs_i}]);"
                # Handle update forms
                if mn.endswith("u"):
                    line += f" ctx->gpr[{base}] += {disp};"
                return line
            return f"/* {mn} unhandled operands: {insn.operands} */;"

        # ------- Indexed Loads -------
        idx_load_map = {
            "lbzx": "vm_read8", "lhzx": "vm_read16", "lwzx": "vm_read32", "ldx": "vm_read64",
            "lhax": "vm_read16", "lwax": "vm_read32",
            "lbzux": "vm_read8", "lhzux": "vm_read16", "lwzux": "vm_read32",
        }
        if mn in idx_load_map:
            helper = idx_load_map[mn]
            rd_i, ra_i, rb_i = _reg_idx(ops[0]), _reg_idx(ops[1]), _reg_idx(ops[2])
            ea = f"(ctx->gpr[{ra_i}] + ctx->gpr[{rb_i}])" if ra_i != "0" else f"ctx->gpr[{rb_i}]"
            expr = f"{helper}({ea})"
            if mn in ("lhax", "lwax"):
                cast = "(int16_t)" if "h" in mn else "(int32_t)"
                expr = f"(int64_t){cast}{expr}"
            return f"ctx->gpr[{rd_i}] = {expr};"

        if mn == "lwa":
            rd_i = _reg_idx(ops[0])
            disp, base = _disp_base(ops[1])
            if disp is not None:
                return f"ctx->gpr[{rd_i}] = (int64_t)(int32_t)vm_read32(ctx->gpr[{base}] + {disp});"

        # ------- Indexed Stores -------
        idx_store_map = {
            "stbx": "vm_write8", "sthx": "vm_write16", "stwx": "vm_write32", "stdx": "vm_write64",
            "stbux": "vm_write8", "sthux": "vm_write16", "stwux": "vm_write32",
        }
        if mn in idx_store_map:
            helper = idx_store_map[mn]
            rs_i, ra_i, rb_i = _reg_idx(ops[0]), _reg_idx(ops[1]), _reg_idx(ops[2])
            ea = f"(ctx->gpr[{ra_i}] + ctx->gpr[{rb_i}])" if ra_i != "0" else f"ctx->gpr[{rb_i}]"
            return f"{helper}({ea}, ctx->gpr[{rs_i}]);"

        # ------- Indexed FP Loads/Stores -------
        if mn in ("lfsx", "lfdx"):
            frd, ra_i, rb_i = _reg_idx(ops[0]), _reg_idx(ops[1]), _reg_idx(ops[2])
            ea = f"(ctx->gpr[{ra_i}] + ctx->gpr[{rb_i}])" if ra_i != "0" else f"ctx->gpr[{rb_i}]"
            if "s" in mn:
                return f"{{ uint32_t tmp = vm_read32({ea}); float ftmp; memcpy(&ftmp, &tmp, 4); ctx->fpr[{frd}] = ftmp; }}"
            else:
                return f"{{ uint64_t tmp = vm_read64({ea}); memcpy(&ctx->fpr[{frd}], &tmp, 8); }}"

        if mn in ("stfsx", "stfdx"):
            frs, ra_i, rb_i = _reg_idx(ops[0]), _reg_idx(ops[1]), _reg_idx(ops[2])
            ea = f"(ctx->gpr[{ra_i}] + ctx->gpr[{rb_i}])" if ra_i != "0" else f"ctx->gpr[{rb_i}]"
            if "s" in mn:
                return f"{{ float ftmp = (float)ctx->fpr[{frs}]; uint32_t tmp; memcpy(&tmp, &ftmp, 4); vm_write32({ea}, tmp); }}"
            else:
                return f"{{ uint64_t tmp; memcpy(&tmp, &ctx->fpr[{frs}], 8); vm_write64({ea}, tmp); }}"

        # ------- Compare -------
        if mn in ("cmpwi", "cmpdi"):
            # ops: [crN,] rA, imm  or  rA, imm
            if ops[0].startswith("cr"):
                bf = int(ops[0][2:])
                ra_i = _reg_idx(ops[1])
                imm = _imm(ops[2])
            else:
                bf = 0
                ra_i = _reg_idx(ops[0])
                imm = _imm(ops[1])
            cast = "(int32_t)" if mn == "cmpwi" else "(int64_t)"
            shift = (7 - bf) * 4
            return (f"{{ int64_t a = {cast}ctx->gpr[{ra_i}]; int64_t b = (int64_t){imm}; "
                    f"uint32_t cr_val = (a < b) ? 8 : (a > b) ? 4 : 2; "
                    f"ctx->cr = (ctx->cr & ~(0xFu << {shift})) | (cr_val << {shift}); }}")

        if mn in ("cmplwi", "cmpldi"):
            if ops[0].startswith("cr"):
                bf = int(ops[0][2:])
                ra_i = _reg_idx(ops[1])
                imm = _imm(ops[2])
            else:
                bf = 0
                ra_i = _reg_idx(ops[0])
                imm = _imm(ops[1])
            cast = "(uint32_t)" if mn == "cmplwi" else "(uint64_t)"
            shift = (7 - bf) * 4
            return (f"{{ uint64_t a = {cast}ctx->gpr[{ra_i}]; uint64_t b = (uint64_t){imm}; "
                    f"uint32_t cr_val = (a < b) ? 8 : (a > b) ? 4 : 2; "
                    f"ctx->cr = (ctx->cr & ~(0xFu << {shift})) | (cr_val << {shift}); }}")

        if mn in ("cmpw", "cmpd"):
            if ops[0].startswith("cr"):
                bf = int(ops[0][2:])
                ra_i = _reg_idx(ops[1])
                rb_i = _reg_idx(ops[2])
            else:
                bf = 0
                ra_i = _reg_idx(ops[0])
                rb_i = _reg_idx(ops[1])
            cast = "(int32_t)" if mn == "cmpw" else "(int64_t)"
            shift = (7 - bf) * 4
            return (f"{{ int64_t a = {cast}ctx->gpr[{ra_i}]; int64_t b = {cast}ctx->gpr[{rb_i}]; "
                    f"uint32_t cr_val = (a < b) ? 8 : (a > b) ? 4 : 2; "
                    f"ctx->cr = (ctx->cr & ~(0xFu << {shift})) | (cr_val << {shift}); }}")

        if mn in ("cmplw", "cmpld"):
            if ops[0].startswith("cr"):
                bf = int(ops[0][2:])
                ra_i = _reg_idx(ops[1])
                rb_i = _reg_idx(ops[2])
            else:
                bf = 0
                ra_i = _reg_idx(ops[0])
                rb_i = _reg_idx(ops[1])
            cast = "(uint32_t)" if mn == "cmplw" else "(uint64_t)"
            shift = (7 - bf) * 4
            return (f"{{ uint64_t a = {cast}ctx->gpr[{ra_i}]; uint64_t b = {cast}ctx->gpr[{rb_i}]; "
                    f"uint32_t cr_val = (a < b) ? 8 : (a > b) ? 4 : 2; "
                    f"ctx->cr = (ctx->cr & ~(0xFu << {shift})) | (cr_val << {shift}); }}")

        # ------- Branches -------
        if mn == "blr" or mn == "blrl":
            return "return;"

        if mn == "b":
            target = ops[0]
            try:
                tgt = int(target, 16)
                if func.start_addr <= tgt < func.end_addr:
                    return f"goto loc_{tgt:08X};"
                else:
                    return f"func_{tgt:08X}(ctx); return;"
            except ValueError:
                return f"goto {target}; /* branch */"

        if mn == "bl":
            target = ops[0]
            try:
                tgt = int(target, 16)
                func.calls.append(tgt)
                self.call_targets.add(tgt)
                return f"func_{tgt:08X}(ctx);"
            except ValueError:
                return f"/* bl {target} */;"

        # Conditional branches
        if mn.startswith("b") and mn not in ("bl", "b", "blr", "bctr", "bctrl"):
            # Try to extract target from last operand
            target_str = ops[-1] if ops else ""
            try:
                tgt = int(target_str, 16)
                if func.start_addr <= tgt < func.end_addr:
                    cond = self._branch_condition(mn, ops)
                    return f"if ({cond}) goto loc_{tgt:08X};"
                else:
                    cond = self._branch_condition(mn, ops)
                    return f"if ({cond}) {{ func_{tgt:08X}(ctx); return; }}"
            except ValueError:
                return f"/* {mn} {insn.operands} */;"

        if mn == "bctr":
            return "/* bctr -- indirect branch via CTR */;"

        if mn == "bctrl":
            return "((void(*)(ppu_context*))ctx->ctr)(ctx);"

        # ------- SPR -------
        if mn == "mflr":
            rd_i = _reg_idx(ops[0])
            return f"ctx->gpr[{rd_i}] = ctx->lr;"

        if mn == "mtlr":
            rs_i = _reg_idx(ops[0])
            return f"ctx->lr = ctx->gpr[{rs_i}];"

        if mn == "mfctr":
            rd_i = _reg_idx(ops[0])
            return f"ctx->gpr[{rd_i}] = ctx->ctr;"

        if mn == "mtctr":
            rs_i = _reg_idx(ops[0])
            return f"ctx->ctr = ctx->gpr[{rs_i}];"

        if mn == "mfcr":
            rd_i = _reg_idx(ops[0])
            return f"ctx->gpr[{rd_i}] = ctx->cr;"

        if mn in ("mtcr", "mtcrf"):
            return f"ctx->cr = (uint32_t)ctx->gpr[{_reg_idx(ops[-1])}];"

        # ------- Syscall -------
        if mn == "sc":
            return "lv2_syscall(ctx);"

        # ------- Floating-point loads/stores -------
        if mn in ("lfs", "lfsu", "lfd", "lfdu"):
            frd = _reg_idx(ops[0])
            disp, base = _disp_base(ops[1])
            if disp is not None:
                if "s" in mn:
                    return (f"{{ uint32_t tmp = vm_read32(ctx->gpr[{base}] + {disp}); "
                            f"float ftmp; memcpy(&ftmp, &tmp, 4); ctx->fpr[{frd}] = ftmp; }}")
                else:
                    return (f"{{ uint64_t tmp = vm_read64(ctx->gpr[{base}] + {disp}); "
                            f"memcpy(&ctx->fpr[{frd}], &tmp, 8); }}")

        if mn in ("stfs", "stfsu", "stfd", "stfdu"):
            frs = _reg_idx(ops[0])
            disp, base = _disp_base(ops[1])
            if disp is not None:
                if "s" in mn:
                    return (f"{{ float ftmp = (float)ctx->fpr[{frs}]; uint32_t tmp; "
                            f"memcpy(&tmp, &ftmp, 4); vm_write32(ctx->gpr[{base}] + {disp}, tmp); }}")
                else:
                    return (f"{{ uint64_t tmp; memcpy(&tmp, &ctx->fpr[{frs}], 8); "
                            f"vm_write64(ctx->gpr[{base}] + {disp}, tmp); }}")

        # ------- FP arithmetic -------
        fp_binary = {
            "fadd": "+", "fadds": "+", "fsub": "-", "fsubs": "-",
            "fmul": "*", "fmuls": "*", "fdiv": "/", "fdivs": "/",
        }
        mn_base = mn.rstrip(".")
        if mn_base in fp_binary:
            frd = _reg_idx(ops[0])
            fra = _reg_idx(ops[1])
            frb = _reg_idx(ops[2])
            op_c = fp_binary[mn_base]
            return f"ctx->fpr[{frd}] = ctx->fpr[{fra}] {op_c} ctx->fpr[{frb}];"

        if mn_base in ("fmr",):
            frd = _reg_idx(ops[0])
            frb = _reg_idx(ops[1])
            return f"ctx->fpr[{frd}] = ctx->fpr[{frb}];"

        if mn_base in ("fneg",):
            frd = _reg_idx(ops[0])
            frb = _reg_idx(ops[1])
            return f"ctx->fpr[{frd}] = -ctx->fpr[{frb}];"

        if mn_base in ("fabs",):
            frd = _reg_idx(ops[0])
            frb = _reg_idx(ops[1])
            return f"ctx->fpr[{frd}] = fabs(ctx->fpr[{frb}]);"

        if mn_base in ("fnabs",):
            frd = _reg_idx(ops[0])
            frb = _reg_idx(ops[1])
            return f"ctx->fpr[{frd}] = -fabs(ctx->fpr[{frb}]);"

        if mn_base in ("fmadd", "fmadds"):
            frd, fra, frc, frb = _reg_idx(ops[0]), _reg_idx(ops[1]), _reg_idx(ops[2]), _reg_idx(ops[3])
            return f"ctx->fpr[{frd}] = ctx->fpr[{fra}] * ctx->fpr[{frc}] + ctx->fpr[{frb}];"

        if mn_base in ("fmsub", "fmsubs"):
            frd, fra, frc, frb = _reg_idx(ops[0]), _reg_idx(ops[1]), _reg_idx(ops[2]), _reg_idx(ops[3])
            return f"ctx->fpr[{frd}] = ctx->fpr[{fra}] * ctx->fpr[{frc}] - ctx->fpr[{frb}];"

        if mn_base in ("fnmadd", "fnmadds"):
            frd, fra, frc, frb = _reg_idx(ops[0]), _reg_idx(ops[1]), _reg_idx(ops[2]), _reg_idx(ops[3])
            return f"ctx->fpr[{frd}] = -(ctx->fpr[{fra}] * ctx->fpr[{frc}] + ctx->fpr[{frb}]);"

        if mn_base in ("fnmsub", "fnmsubs"):
            frd, fra, frc, frb = _reg_idx(ops[0]), _reg_idx(ops[1]), _reg_idx(ops[2]), _reg_idx(ops[3])
            return f"ctx->fpr[{frd}] = -(ctx->fpr[{fra}] * ctx->fpr[{frc}] - ctx->fpr[{frb}]);"

        if mn_base in ("frsp",):
            frd = _reg_idx(ops[0])
            frb = _reg_idx(ops[1])
            return f"ctx->fpr[{frd}] = (float)ctx->fpr[{frb}];"

        if mn_base in ("fctiwz",):
            frd = _reg_idx(ops[0])
            frb = _reg_idx(ops[1])
            return (f"{{ int32_t iv = (int32_t)ctx->fpr[{frb}]; uint64_t tmp; "
                    f"memcpy(&tmp, &ctx->fpr[{frd}], 8); "
                    f"tmp = (tmp & 0xFFFFFFFF00000000ULL) | (uint32_t)iv; "
                    f"memcpy(&ctx->fpr[{frd}], &tmp, 8); }}")

        if mn_base in ("fctid", "fctidz"):
            frd = _reg_idx(ops[0])
            frb = _reg_idx(ops[1])
            return (f"{{ int64_t iv = (int64_t)ctx->fpr[{frb}]; "
                    f"memcpy(&ctx->fpr[{frd}], &iv, 8); }}")

        if mn_base in ("fcfid",):
            frd = _reg_idx(ops[0])
            frb = _reg_idx(ops[1])
            return (f"{{ int64_t iv; memcpy(&iv, &ctx->fpr[{frb}], 8); "
                    f"ctx->fpr[{frd}] = (double)iv; }}")

        if mn_base == "fsqrt" or mn_base == "fsqrts":
            frd = _reg_idx(ops[0])
            frb = _reg_idx(ops[1])
            return f"ctx->fpr[{frd}] = sqrt(ctx->fpr[{frb}]);"

        if mn_base == "fsel":
            frd, fra, frc, frb = _reg_idx(ops[0]), _reg_idx(ops[1]), _reg_idx(ops[2]), _reg_idx(ops[3])
            return f"ctx->fpr[{frd}] = (ctx->fpr[{fra}] >= 0.0) ? ctx->fpr[{frc}] : ctx->fpr[{frb}];"

        # ------- FP compare -------
        if mn_base == "fcmpu" or mn_base == "fcmpo":
            if ops[0].startswith("cr"):
                bf = int(ops[0][2:])
                fra = _reg_idx(ops[1])
                frb = _reg_idx(ops[2])
            else:
                bf = 0
                fra = _reg_idx(ops[0])
                frb = _reg_idx(ops[1])
            shift = (7 - bf) * 4
            return (f"{{ double a = ctx->fpr[{fra}]; double b = ctx->fpr[{frb}]; "
                    f"uint32_t cr_val = (a < b) ? 8 : (a > b) ? 4 : 2; "
                    f"ctx->cr = (ctx->cr & ~(0xFu << {shift})) | (cr_val << {shift}); }}")

        # ------- Default: emit as comment -------
        return f"/* TODO: {mn} {insn.operands} */;"

    def _branch_condition(self, mnemonic: str, ops: list[str]) -> str:
        """Generate a C condition expression for a conditional branch."""
        mn = mnemonic.rstrip("la")  # strip link and absolute bits
        if mn.startswith("b"):
            mn = mn[1:]  # strip leading 'b'

        # strip trailing 'lr', 'ctr'
        mn = mn.replace("lr", "").replace("ctr", "")

        cr_field = 0
        # Check if first operand is a CR field
        if ops and ops[0].startswith("cr"):
            try:
                cr_field = int(ops[0][2:])
            except ValueError:
                pass

        shift = (7 - cr_field) * 4

        cond_map = {
            "eq": f"((ctx->cr >> {shift}) & 2)",
            "ne": f"(!((ctx->cr >> {shift}) & 2))",
            "lt": f"((ctx->cr >> {shift}) & 8)",
            "ge": f"(!((ctx->cr >> {shift}) & 8))",
            "gt": f"((ctx->cr >> {shift}) & 4)",
            "le": f"(!((ctx->cr >> {shift}) & 4))",
            "so": f"((ctx->cr >> {shift}) & 1)",
            "ns": f"(!((ctx->cr >> {shift}) & 1))",
            "dnz": "(--(ctx->ctr) != 0)",
            "dz": "(--(ctx->ctr) == 0)",
        }

        return cond_map.get(mn, f"/* cond: {mnemonic} */ 1")

    # ------------------------------------------------------------------ #
    # Output generation
    # ------------------------------------------------------------------ #

    def emit_header(self) -> str:
        """Generate the C header file content."""
        lines = [HEADER_PREAMBLE]
        # Forward declarations
        for func in self.functions:
            lines.append(f"void {func.name}(ppu_context* ctx);")
        # Also declare any call targets that aren't defined
        defined = {f.start_addr for f in self.functions}
        for target in sorted(self.call_targets - defined):
            lines.append(f"void func_{target:08X}(ppu_context* ctx); /* external */")
        lines.append("")
        return "\n".join(lines)

    def emit_source(self) -> str:
        """Generate the C source file content."""
        lines = [SOURCE_PREAMBLE]

        # Emit helper macros
        lines.append("/* Rotate helpers */")
        lines.append("static inline uint32_t ppc_rlwinm(uint32_t rs, int sh, int mb, int me) {")
        lines.append("    uint32_t rotated = (rs << sh) | (rs >> (32 - sh));")
        lines.append("    uint32_t mask;")
        lines.append("    if (mb <= me) {")
        lines.append("        mask = ((uint32_t)-1 >> mb) & ((uint32_t)-1 << (31 - me));")
        lines.append("    } else {")
        lines.append("        mask = ((uint32_t)-1 >> mb) | ((uint32_t)-1 << (31 - me));")
        lines.append("    }")
        lines.append("    return rotated & mask;")
        lines.append("}")
        lines.append("")
        lines.append("static inline uint32_t ppc_rlwimi(uint32_t ra, uint32_t rs, int sh, int mb, int me) {")
        lines.append("    uint32_t rotated = (rs << sh) | (rs >> (32 - sh));")
        lines.append("    uint32_t mask;")
        lines.append("    if (mb <= me) {")
        lines.append("        mask = ((uint32_t)-1 >> mb) & ((uint32_t)-1 << (31 - me));")
        lines.append("    } else {")
        lines.append("        mask = ((uint32_t)-1 >> mb) | ((uint32_t)-1 << (31 - me));")
        lines.append("    }")
        lines.append("    return (rotated & mask) | (ra & ~mask);")
        lines.append("}")
        lines.append("")
        # 64-bit rotate helpers
        lines.append("/* 64-bit rotate helpers */")
        lines.append("static inline uint64_t ppc_rotl64(uint64_t v, int n) {")
        lines.append("    n &= 63;")
        lines.append("    return (v << n) | (v >> (64 - n));")
        lines.append("}")
        lines.append("static inline uint64_t ppc_mask64(int mb, int me) {")
        lines.append("    uint64_t mask;")
        lines.append("    if (mb <= me) {")
        lines.append("        mask = (mb == 0) ? ~0ULL : (~0ULL >> mb);")
        lines.append("        mask &= (me == 63) ? ~0ULL : (~0ULL << (63 - me));")
        lines.append("    } else {")
        lines.append("        mask = (~0ULL >> mb) | (~0ULL << (63 - me));")
        lines.append("    }")
        lines.append("    return mask;")
        lines.append("}")
        lines.append("static inline uint64_t ppc_rldicl(uint64_t rs, int sh, int mb) {")
        lines.append("    return ppc_rotl64(rs, sh) & ppc_mask64(mb, 63);")
        lines.append("}")
        lines.append("static inline uint64_t ppc_rldicr(uint64_t rs, int sh, int me) {")
        lines.append("    return ppc_rotl64(rs, sh) & ppc_mask64(0, me);")
        lines.append("}")
        lines.append("static inline uint64_t ppc_rldic(uint64_t rs, int sh, int mb) {")
        lines.append("    int me = 63 - sh;")
        lines.append("    return ppc_rotl64(rs, sh) & ppc_mask64(mb, me);")
        lines.append("}")
        lines.append("static inline uint64_t ppc_rldimi(uint64_t ra, uint64_t rs, int sh, int mb) {")
        lines.append("    int me = 63 - sh;")
        lines.append("    uint64_t mask = ppc_mask64(mb, me);")
        lines.append("    return (ppc_rotl64(rs, sh) & mask) | (ra & ~mask);")
        lines.append("}")
        lines.append("")

        for func in self.functions:
            lines.append(f"void {func.name}(ppu_context* ctx) {{")
            for bline in func.body_lines:
                lines.append(f"    {bline}" if not bline.endswith(":") else bline)
            lines.append("}")
            lines.append("")

        # Function table
        lines.append("/* Function table */")
        lines.append("typedef struct { uint64_t addr; void (*func)(ppu_context*); const char* name; } func_entry;")
        lines.append(f"static const func_entry function_table[] = {{")
        for func in self.functions:
            lines.append(f'    {{ 0x{func.start_addr:08X}ULL, {func.name}, "{func.name}" }},')
        lines.append("    { 0, NULL, NULL }")
        lines.append("};")
        lines.append("")

        return "\n".join(lines)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(description="PPU to C lifter for PS3 recompilation")
    parser.add_argument("input", help="Input ELF or raw binary")
    parser.add_argument("--output", "-o", default=".", help="Output directory")
    parser.add_argument("--header-name", default="ppu_recomp.h", help="Header file name")
    parser.add_argument("--source-name", default="ppu_recomp.c", help="Source file name")
    parser.add_argument("--raw", action="store_true", help="Treat input as raw binary")
    parser.add_argument("--base", type=lambda x: int(x, 0), default=0,
                        help="Base address (for raw binary)")
    parser.add_argument("--little-endian", action="store_true")
    parser.add_argument("--functions", metavar="FILE",
                        help="JSON file with function list [{start, end}, ...]")
    args = parser.parse_args()

    with open(args.input, "rb") as f:
        file_data = f.read()

    big_endian = not args.little_endian
    base_addr = args.base

    # Get instructions
    if args.raw:
        all_insns = disassemble_bytes(file_data, base_addr, big_endian)
    else:
        try:
            from elf_parser import ELFFile, PT_LOAD
            elf = ELFFile(args.input)
            elf.load()
            big_endian = elf.elf_header.big_endian
            all_insns = []
            for ph in elf.program_headers:
                if ph.p_type == PT_LOAD and (ph.p_flags & 1):
                    seg_data = elf.get_segment_data(elf.program_headers.index(ph))
                    all_insns.extend(disassemble_bytes(seg_data, ph.p_vaddr, big_endian))
            if not all_insns:
                for ph in elf.program_headers:
                    if ph.p_type == PT_LOAD and ph.p_filesz > 0:
                        seg_data = elf.get_segment_data(elf.program_headers.index(ph))
                        all_insns.extend(disassemble_bytes(seg_data, ph.p_vaddr, big_endian))
                        break
        except Exception as exc:
            print(f"Warning: ELF parse failed ({exc}), treating as raw", file=sys.stderr)
            all_insns = disassemble_bytes(file_data, base_addr, big_endian)

    # Get function boundaries
    if args.functions:
        with open(args.functions) as f:
            func_list = json.load(f)
        func_bounds = [(int(str(e["start"]), 0), int(str(e["end"]), 0)) for e in func_list]
    else:
        detected = detect_functions(all_insns)
        func_bounds = [(f["start"], f["end"]) for f in detected]

    if not func_bounds:
        print("No functions found. Use --functions to provide a function list.", file=sys.stderr)
        sys.exit(1)

    print(f"Lifting {len(func_bounds)} functions...")

    lifter = PPULifter()
    for start, end in func_bounds:
        lifter.lift_function(all_insns, start, end)

    os.makedirs(args.output, exist_ok=True)

    header_path = os.path.join(args.output, args.header_name)
    source_path = os.path.join(args.output, args.source_name)

    with open(header_path, "w") as f:
        f.write(lifter.emit_header())

    with open(source_path, "w") as f:
        f.write(lifter.emit_source())

    print(f"Wrote {header_path}")
    print(f"Wrote {source_path}")
    print(f"  {len(lifter.functions)} functions lifted")
    print(f"  {len(lifter.call_targets)} unique call targets")


if __name__ == "__main__":
    main()
