#!/usr/bin/env python3
"""
SPU instruction lifter -- translates SPU disassembly into C code for the
ps3recomp static-recompilation runtime.

Mirrors the design of ppu_lifter.py:
  * Each original SPU function is emitted as a C function taking a
    ``spu_context*`` parameter (see runtime/spu/spu_context.h).
  * Instruction semantics live in small ``static inline u128 spu_*`` helper
    functions emitted into the source preamble; the per-instruction
    translator just wires guest registers to those helpers.  This keeps the
    generated function bodies readable and the semantics unit-testable.
  * Control flow uses the same trampoline pattern as the PPU lifter to avoid
    unbounded host-stack growth on backward branches.

SPU register model
------------------
  * 128 registers, each a 128-bit ``u128`` union (lanes: _u32[4], _u16[8],
    _u8[16], _s32[4], _f32[4], ...).
  * Most arithmetic is SIMD across the natural lane width (word = 4x32,
    halfword = 8x16, byte = 16x8).
  * Scalar / addressing instructions use the *preferred slot* = word lane 0
    (``reg._u32[0]``), matching spu_preferred_u32() in spu_context.h.

Scope (Phase 1)
---------------
Implemented faithfully: immediates, integer add/sub (word+half, +imm),
bitwise logic (+imm), compares (eq/gt/lgt for byte/half/word, +imm), select
(selb), byte shuffle (shufb), count-leading-zeros / popcount, the common
shift/rotate-immediate forms, single-precision float add/sub/mul and the
fused multiply forms, quadword load/store (d-form, absolute, indexed),
branches (relative/absolute/conditional/indirect, with link), stop/nop/sync.

Emitted as runtime calls (declared extern, implemented by the runtime):
channel ops (rdch/wrch/rchcnt -> MFC DMA, mailboxes, signals) and indirect
branch dispatch.

Anything not yet handled is emitted as a ``/* TODO spu: ... */`` comment so
the gap is visible in the generated source and counted in the CLI summary.

Usage:
    python spu_lifter.py <input_bin> [--base ADDR] [--output dir]
                         [--functions FILE]
"""

import argparse
import json
import os
import re
import sys
from dataclasses import dataclass, field

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

try:
    from spu_disasm import SPUInstruction, disassemble_spu, spu_decode, CHANNEL_NAMES
except ImportError:
    print("Error: spu_disasm.py must be in the same directory.", file=sys.stderr)
    sys.exit(1)

# Channel macro names defined in runtime/spu/spu_context.h. When the
# disassembler hands us one of these, we can emit it verbatim as a macro.
_CHANNEL_MACROS = set(CHANNEL_NAMES.values())

# ---------------------------------------------------------------------------
# C preambles
# ---------------------------------------------------------------------------

HEADER_PREAMBLE = """\
/* Auto-generated by spu_lifter.py -- do not edit by hand. */
#pragma once
#include "../../runtime/spu/spu_context.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Indirect branch dispatch (bi/bisl/bid...): PC has been set to the target
 * local-store address; the runtime resolves it to the matching lifted
 * function and continues execution. Implemented by the SPU program glue. */
void spu_indirect_branch(spu_context* ctx);

/* Channel access -- implemented by the runtime (MFC DMA engine, mailboxes,
 * signal notification, decrementer). See runtime/spu/spu_dma.h. */
u128 spu_rdch(spu_context* ctx, uint32_t channel);
uint32_t spu_rchcnt(spu_context* ctx, uint32_t channel);
void spu_wrch(spu_context* ctx, uint32_t channel, u128 value);

/* Execution trace (only emitted when the lifter was invoked with --trace). */
void spu_trace_init(const char* path);
void spu_trace_pc(spu_context* ctx, uint32_t pc);
void spu_trace_rt(spu_context* ctx, uint32_t rt);

#ifdef __cplusplus
}
#endif
"""

# NOTE on endianness: spu_context.h treats word lane 0 as the preferred slot
# and its local-store helpers copy raw bytes (big-endian in the guest image).
# The helpers below operate lane-wise, which is internally consistent as long
# as loads/stores use the same lane convention. A host that is not big-endian
# will need byte-swapping in the LS helpers -- that is a runtime concern, out
# of scope for the lifter.
SOURCE_PREAMBLE = """/* Auto-generated by spu_lifter.py -- do not edit by hand. */
#include "spu_recomp.h"
#include "../../runtime/spu/spu_helpers.h"
"""

# ---------------------------------------------------------------------------
# Operand helpers
# ---------------------------------------------------------------------------

def _ops(operands: str) -> list[str]:
    return [o.strip() for o in operands.split(",") if o.strip()]


def _reg(token: str) -> str:
    """'$r12' -> '12'."""
    m = re.match(r"\$r(\d+)", token.strip())
    return m.group(1) if m else token.strip()


def _disp_base(token: str):
    """'0x10($r4)' or '-0x10($r4)' -> ('0x10', '4')."""
    m = re.match(r"(-?0x[0-9A-Fa-f]+|-?\d+)\(\$r(\d+)\)", token.strip())
    if m:
        return m.group(1), m.group(2)
    return None, None


def _imm(token: str) -> str:
    token = token.strip()
    if token.startswith("0x") or token.startswith("-0x"):
        return token
    try:
        return str(int(token))
    except ValueError:
        return token


def _chan(token: str) -> str:
    """Channel operand -> a C expression (macro name or numeric id)."""
    token = token.strip()
    if token in _CHANNEL_MACROS:
        return token
    m = re.match(r"ch(\d+)", token)
    if m:
        return m.group(1)
    return token

# ---------------------------------------------------------------------------
# Lifter
# ---------------------------------------------------------------------------

@dataclass
class LiftedFunction:
    name: str = ""
    start_addr: int = 0
    end_addr: int = 0
    body_lines: list[str] = field(default_factory=list)
    calls: list[int] = field(default_factory=list)


# Mnemonics whose last operand is a branch target address (0x...).
_COND_BR = {"brz", "brnz", "brhz", "brhnz"}


# Mnemonics that do NOT write the rt register (so we skip the post-trace).
# Everything else writes rt = ops[0] (= insn.raw & 0x7F).
_NO_RT_WRITE = {
    "stop", "stopd", "lnop", "nop", "sync", "dsync",
    "bi", "iret", "biz", "binz", "bihz", "bihnz",
    "br", "bra", "brz", "brnz", "brhz", "brhnz",
    "hbr", "hbra", "hbrr",
    "stqd", "stqa", "stqr", "stqx",
    "wrch",
    "hgt", "hlgt", "heq", "hgti", "hlgti", "heqi",
}


class SPULifter:
    def __init__(self, trace: bool = False):
        self.functions: list[LiftedFunction] = []
        self.call_targets: set[int] = set()
        self.branch_targets: set[int] = set()
        self.unsupported: dict[str, int] = {}
        self.trace = trace

    # ------------------------------------------------------------------ #
    def lift_function(self, insns: list[SPUInstruction],
                      start: int, end: int) -> LiftedFunction:
        func = LiftedFunction(name=f"spu_func_{start:08X}",
                              start_addr=start, end_addr=end)

        internal: set[int] = set()
        for insn in insns:
            if insn.addr < start or insn.addr >= end:
                continue
            tgt = self._branch_target(insn)
            if tgt is not None and start <= tgt < end:
                internal.add(tgt)

        for insn in insns:
            if insn.addr < start or insn.addr >= end:
                continue
            if insn.addr in internal:
                func.body_lines.append(f"loc_{insn.addr:08X}:")
            c = self._translate(insn, func)
            if c:
                if self.trace:
                    func.body_lines.append(f"    spu_trace_pc(ctx, 0x{insn.addr:X});")
                func.body_lines.append(f"    {c}")
                if self.trace and insn.mnemonic not in _NO_RT_WRITE:
                    rt_idx = insn.raw & 0x7F
                    func.body_lines.append(f"    spu_trace_rt(ctx, {rt_idx});")

        self.functions.append(func)
        return func

    @staticmethod
    def _branch_target(insn: SPUInstruction):
        mn = insn.mnemonic
        ops = _ops(insn.operands)
        tok = None
        if mn in ("br", "brsl", "bra", "brasl") and ops:
            tok = ops[0]
        elif mn in _COND_BR and ops:
            tok = ops[-1]
        if tok and tok.startswith("0x"):
            try:
                return int(tok, 16)
            except ValueError:
                return None
        return None

    # ------------------------------------------------------------------ #
    def _translate(self, insn: SPUInstruction, func: LiftedFunction) -> str:
        mn = insn.mnemonic
        ops = _ops(insn.operands)
        addr = insn.addr

        def rt(): return _reg(ops[0])
        def ra(): return _reg(ops[1])
        def rb(): return _reg(ops[2])
        def g(i): return f"ctx->gpr[{i}]"

        # ---- nop / sync / stop ----
        if mn in ("nop", "lnop"):
            return "/* nop */;"
        if mn in ("sync", "dsync"):
            return "/* sync */;"
        if mn == "stop":
            return "ctx->status = SPU_STATUS_STOPPED_BY_STOP; return;"

        # ---- immediate loaders ----
        if mn == "il":
            return f"{g(rt())} = spu_il({_imm(ops[1])});"
        if mn == "ila":
            return f"{g(rt())} = spu_ila({_imm(ops[1])});"
        if mn == "ilh":
            return f"{g(rt())} = spu_ilh({_imm(ops[1])});"
        if mn == "ilhu":
            return f"{g(rt())} = spu_ilhu({_imm(ops[1])});"
        if mn == "iohl":
            return f"{g(rt())} = spu_iohl({g(rt())}, {_imm(ops[1])});"
        if mn == "fsmbi":
            return f"{g(rt())} = spu_fsmbi({_imm(ops[1])});"

        # addx / bgx: read rt as carry-in (and write rt)
        if mn == "addx":
            return f"{g(rt())} = spu_addx({g(ra())}, {g(rb())}, {g(rt())});"
        if mn == "bgx":
            return f"{g(rt())} = spu_bgx({g(ra())}, {g(rb())}, {g(rt())});"

        # Halt-on-condition + stopd: pure stop semantics in recompiled code;
        # we just continue execution (no host halt path for these yet).
        if mn in ("hgti", "hlgti", "heqi", "hgt", "hlgt", "heq"):
            return f"/* {mn}: halt-on-condition (no-op in recomp) */;"
        if mn == "stopd":
            return "ctx->status = SPU_STATUS_STOPPED_BY_STOP; return;"

        # ---- integer arithmetic (register) ----
        rr_bin = {
            "a": "spu_a", "sf": "spu_sf", "ah": "spu_ah", "sfh": "spu_sfh",
            "and": "spu_and", "or": "spu_or", "xor": "spu_xor",
            "nand": "spu_nand", "nor": "spu_nor", "andc": "spu_andc", "orc": "spu_orc",
            "ceq": "spu_ceq", "ceqh": "spu_ceqh", "ceqb": "spu_ceqb",
            "cgt": "spu_cgt", "cgth": "spu_cgth", "cgtb": "spu_cgtb",
            "clgt": "spu_clgt", "clgth": "spu_clgth", "clgtb": "spu_clgtb",
            "mpy": "spu_mpy", "mpyu": "spu_mpyu",
            "mpyh": "spu_mpyh", "mpyhh": "spu_mpyhh", "mpys": "spu_mpys",
            "fa": "spu_fa", "fs": "spu_fs", "fm": "spu_fm",
            "fceq": "spu_fceq", "fcgt": "spu_fcgt",
            "fcmeq": "spu_fcmeq", "fcmgt": "spu_fcmgt",
            "cg": "spu_cg",
            # Phase 2: register-variable shifts/rotates
            "shl": "spu_shl", "shlh": "spu_shlh",
            "rot": "spu_rot", "roth": "spu_roth",
            "shlqbi": "spu_shlqbi",  "rotqbi": "spu_rotqbi",
            "shlqby": "spu_shlqby",  "rotqby": "spu_rotqby",
            "shlqbybi": "spu_shlqbybi", "rotqbybi": "spu_rotqbybi",
            # Phase 3: rotate-and-mask (register-variable)
            "rotm": "spu_rotm", "rotma": "spu_rotma",
            "rothm": "spu_rothm", "rothma": "spu_rothma",
            "rotqmbi": "spu_rotqmbi", "rotqmby": "spu_rotqmby",
            "rotqmbybi": "spu_rotqmbybi",
            # Phase 3: indexed constant generators (insertion masks)
            "cbx": "spu_cbx", "chx": "spu_chx",
            "cwx": "spu_cwx", "cdx": "spu_cdx",
        }
        if mn in rr_bin:
            return f"{g(rt())} = {rr_bin[mn]}({g(ra())}, {g(rb())});"

        # ---- unary (register) ----
        rr_un = {
            "clz": "spu_clz", "cntb": "spu_cntb",
            "fscrrd": "spu_fscrrd",
            "gb": "spu_gb", "gbh": "spu_gbh",
            "frsqest": "spu_frsqest",
            # Phase 3
            "xsbh": "spu_xsbh", "xshw": "spu_xshw", "xswd": "spu_xswd",
            "orx": "spu_orx",
            "fsm": "spu_fsm", "fsmh": "spu_fsmh", "fsmb": "spu_fsmb",
            "mfspr": "spu_mfspr",
        }
        if mn in rr_un:
            return f"{g(rt())} = {rr_un[mn]}({g(ra())});"

        # ---- move register (or rt,ra,ra) handled by generic 'or' above ----

        # ---- arithmetic / logical / compare immediate ----
        ri_imm = {
            "ai": "spu_ai", "ahi": "spu_ahi", "sfi": "spu_sfi", "sfhi": "spu_sfhi",
            "andi": "spu_andi", "ori": "spu_ori", "xori": "spu_xori",
            "ceqi": "spu_ceqi", "cgti": "spu_cgti", "clgti": "spu_clgti",
            "ceqbi": "spu_ceqbi", "ceqhi": "spu_ceqhi",
            "clgtbi": "spu_clgtbi", "clgthi": "spu_clgthi",
            "mpyi": "spu_mpyi", "mpyui": "spu_mpyui",
            # Phase 3: halfword/byte immediate logic
            "andhi": "spu_andhi", "andbi": "spu_andbi",
            "orhi":  "spu_orhi",  "orbi":  "spu_orbi",
            "xorhi": "spu_xorhi",
        }
        if mn in ri_imm:
            return f"{g(rt())} = {ri_imm[mn]}({g(ra())}, {_imm(ops[2])});"

        # ---- shift / rotate immediate ----
        sh_imm = {
            "shli": "spu_shli", "shlhi": "spu_shlhi",
            "roti": "spu_roti", "rothi": "spu_rothi",
            "rotmi": "spu_rotmi", "rotmai": "spu_rotmai", "rotmhi": "spu_rotmhi",
            "rotmahi": "spu_rotmahi",
            "shlqbyi": "spu_shlqbyi", "rotqbyi": "spu_rotqbyi",
            "shlqbii": "spu_shlqbii", "rotqbii": "spu_rotqbii",
            # Phase 3: rotate-and-mask immediate + d-form constant generators
            "rothmi": "spu_rothmi",
            "rotqmbii": "spu_rotqmbii", "rotqmbyi": "spu_rotqmbyi",
            "cbd": "spu_cbd", "chd": "spu_chd",
            "cwd": "spu_cwd", "cdd": "spu_cdd",
        }
        if mn in sh_imm:
            # Disassembler quirk: the quad shift/rotate RI7 forms (shlqbyi,
            # rotqbyi, shlqbii, rotqbii) are matched against SPU_RR first and
            # therefore emitted with 3-register operands, with the i7 bits
            # disguised as "$rN". The register index IS the immediate value,
            # so we strip the "$r" and use the digits literally.
            tok = ops[2]
            if tok.startswith("$r"):
                tok = tok[2:]
            else:
                tok = _imm(tok)
            return f"{g(rt())} = {sh_imm[mn]}({g(ra())}, {tok});"

        # ---- select / shuffle (RRR: rt, ra, rb, rc) ----
        if mn == "selb":
            rc = _reg(ops[3])
            return f"{g(rt())} = spu_selb({g(ra())}, {g(rb())}, {g(rc)});"
        if mn == "shufb":
            rc = _reg(ops[3])
            return f"{g(rt())} = spu_shufb({g(ra())}, {g(rb())}, {g(rc)});"
        if mn in ("fma", "fms", "fnms"):
            rc = _reg(ops[3])
            return f"{g(rt())} = spu_{mn}({g(ra())}, {g(rb())}, {g(rc)});"

        # ---- quadword loads / stores ----
        if mn == "lqd":
            disp, base = _disp_base(ops[1])
            if disp is not None:
                return f"{g(rt())} = spu_ls_read128(ctx, {g(base)}._u32[0] + {disp});"
        if mn == "stqd":
            disp, base = _disp_base(ops[1])
            if disp is not None:
                return f"spu_ls_write128(ctx, {g(base)}._u32[0] + {disp}, {g(rt())});"
        if mn in ("lqa", "lqr"):
            return f"{g(rt())} = spu_ls_read128(ctx, {_imm(ops[1])});"
        if mn in ("stqa", "stqr"):
            return f"spu_ls_write128(ctx, {_imm(ops[1])}, {g(rt())});"
        if mn == "lqx":
            return f"{g(rt())} = spu_ls_read128(ctx, {g(ra())}._u32[0] + {g(rb())}._u32[0]);"
        if mn == "stqx":
            return f"spu_ls_write128(ctx, {g(ra())}._u32[0] + {g(rb())}._u32[0], {g(rt())});"

        # ---- channel ops ----
        if mn == "rdch":
            return f"{g(rt())} = spu_rdch(ctx, {_chan(ops[1])});"
        if mn == "rchcnt":
            return f"{g(rt())} = spu_splat_u32(spu_rchcnt(ctx, {_chan(ops[1])}));"
        if mn == "wrch":
            # operands: channel, $rt
            return f"spu_wrch(ctx, {_chan(ops[0])}, {g(_reg(ops[1]))});"

        # ---- branches ----
        if mn in ("br", "bra"):
            tgt = self._branch_target(insn)
            return self._uncond_branch(tgt, func)
        if mn in ("brsl", "brasl"):
            # The disassembler drops the link register from brsl operands, so
            # recover it from the raw encoding (rt = bits 25-31 = raw & 0x7F).
            link_rt = insn.raw & 0x7F
            tgt = self._branch_target(insn)
            link = f"{g(link_rt)} = spu_splat_u32(0x{addr + 4:X});"
            if tgt is not None:
                self.call_targets.add(tgt)
                return f"{link} spu_func_{tgt:08X}(ctx);"
            return f"{link} /* TODO spu: brsl unresolved target */;"
        if mn in _COND_BR:
            tgt = self._branch_target(insn)
            cond = self._cond(mn, _reg(ops[0]))
            if tgt is None:
                return f"/* TODO spu: {mn} {insn.operands} */;"
            if func.start_addr <= tgt < func.end_addr:
                return f"if ({cond}) goto loc_{tgt:08X};"
            self.branch_targets.add(tgt)
            return (f"if ({cond}) {{ ctx->pc = 0x{tgt:X}; "
                    f"spu_func_{tgt:08X}(ctx); return; }}")
        # For bi/bisl the disassembler emits only "$rA" (ops[0] = target reg).
        if mn in ("bi",):
            tgt_reg = _reg(ops[0])
            # SPU ABI: $r0 is the link register. `bi $r0` is the standard
            # function return — translate to a host return so call/return
            # discipline matches the C function nesting from brsl.
            if tgt_reg == "0":
                return "return;"
            return (f"ctx->pc = {g(tgt_reg)}._u32[0]; "
                    f"spu_indirect_branch(ctx); return;")
        if mn in ("bisl",):
            link_rt = insn.raw & 0x7F            # link reg dropped from operands
            tgt_reg = _reg(ops[0])
            return (f"{g(link_rt)} = spu_splat_u32(0x{addr + 4:X}); "
                    f"ctx->pc = {g(tgt_reg)}._u32[0]; spu_indirect_branch(ctx);")
        # biz/binz/bihz/bihnz: ops[0] = condition reg, ops[1] = target reg.
        if mn in ("biz", "binz", "bihz", "bihnz"):
            cond = self._cond(mn[1:], _reg(ops[0]))   # strip leading 'b' -> iz/inz...
            tgt_reg = _reg(ops[1])
            return (f"if ({cond}) {{ ctx->pc = {g(tgt_reg)}._u32[0]; "
                    f"spu_indirect_branch(ctx); return; }}")

        # hint-for-branch: pure performance hint, safe to drop
        if mn in ("hbr", "hbra", "hbrr"):
            return "/* branch hint (ignored) */;"

        # ---- fallthrough: unsupported ----
        self.unsupported[mn] = self.unsupported.get(mn, 0) + 1
        return f"/* TODO spu: {mn} {insn.operands} */;"

    # ------------------------------------------------------------------ #
    def _cond(self, mn: str, reg: str) -> str:
        """Condition expression on preferred slot for conditional branches."""
        word = f"ctx->gpr[{reg}]._u32[0]"
        half = f"ctx->gpr[{reg}]._u16[1]"   # preferred halfword (lane 1 of word 0)
        table = {
            "brz": f"{word} == 0",      "brnz": f"{word} != 0",
            "brhz": f"{half} == 0",     "brhnz": f"{half} != 0",
            "iz": f"{word} == 0",       "inz": f"{word} != 0",
            "ihz": f"{half} == 0",      "ihnz": f"{half} != 0",
        }
        return table.get(mn, f"{word} != 0")

    def _uncond_branch(self, tgt, func: LiftedFunction) -> str:
        if tgt is None:
            return "/* TODO spu: unresolved branch */;"
        if func.start_addr <= tgt < func.end_addr:
            return f"goto loc_{tgt:08X};"
        self.branch_targets.add(tgt)
        return f"{{ ctx->pc = 0x{tgt:X}; spu_func_{tgt:08X}(ctx); return; }}"

    # ------------------------------------------------------------------ #
    def emit_header(self) -> str:
        lines = [HEADER_PREAMBLE, ""]
        for f in self.functions:
            lines.append(f"void {f.name}(spu_context* ctx);")
        defined = {f.start_addr for f in self.functions}
        for t in sorted(self.call_targets | self.branch_targets):
            if t not in defined:
                lines.append(f"void spu_func_{t:08X}(spu_context* ctx); /* external */")
        lines.append("")
        lines.append("/* Runtime glue (runtime/spu/spu_channels.c) */")
        lines.append("void spu_register_function(uint32_t addr, void (*fn)(spu_context*));")
        lines.append("/* Call once at init to register this image's functions for")
        lines.append(" * indirect-branch dispatch (spu_indirect_branch). */")
        lines.append("void spu_recomp_register(void);")
        lines.append("")
        return "\n".join(lines)

    def emit_source(self) -> str:
        lines = [SOURCE_PREAMBLE, ""]
        for f in self.functions:
            lines.append(f"void {f.name}(spu_context* ctx) {{")
            for b in f.body_lines:
                lines.append(b if b.endswith(":") else f"    {b}")
            lines.append("}")
            lines.append("")

        # Stubs for cross-function branch/call targets the function-boundary
        # detector did not promote to standalone functions. The lifter emits
        # `spu_func_<tgt>(ctx)` calls eagerly, so the linker needs a symbol;
        # at runtime we route through spu_indirect_branch which either lands
        # on a registered mid-function entry (if one was emitted) or halts
        # cleanly with a "PC X not registered" diagnostic.
        defined = {f.start_addr for f in self.functions}
        externs = sorted((self.call_targets | self.branch_targets) - defined)
        if externs:
            lines.append("/* Indirect-dispatch stubs for cross-function targets the")
            lines.append(" * function detector did not seed (typically conditional")
            lines.append(" * branches that escape a function's range). */")
            for t in externs:
                lines.append(f"void spu_func_{t:08X}(spu_context* ctx) {{")
                lines.append(f"    ctx->pc = 0x{t:X}u; spu_indirect_branch(ctx);")
                lines.append("}")
            lines.append("")

        lines.append("/* Function table */")
        lines.append("typedef struct { uint32_t addr; void (*func)(spu_context*); const char* name; } spu_func_entry;")
        lines.append("static const spu_func_entry spu_function_table[] = {")
        for f in self.functions:
            lines.append(f'    {{ 0x{f.start_addr:08X}u, {f.name}, "{f.name}" }},')
        lines.append("    { 0, NULL, NULL }")
        lines.append("};")
        lines.append("")
        lines.append("void spu_recomp_register(void) {")
        lines.append("    for (const spu_func_entry* e = spu_function_table; e->func; ++e)")
        lines.append("        spu_register_function(e->addr, e->func);")
        lines.append("}")
        lines.append("")
        return "\n".join(lines)

# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> None:
    p = argparse.ArgumentParser(description="SPU to C lifter for ps3recomp")
    p.add_argument("input", nargs="?", default=None,
                   help="Raw SPU binary (local-store image) or segment. "
                        "Omit if --auto-functions is set.")
    p.add_argument("--output", "-o", default=".", help="Output directory")
    p.add_argument("--header-name", default="spu_recomp.h")
    p.add_argument("--source-name", default="spu_recomp.c")
    p.add_argument("--base", type=lambda x: int(x, 0), default=0,
                   help="Base local-store address")
    p.add_argument("--offset", type=lambda x: int(x, 0), default=0)
    p.add_argument("--length", type=lambda x: int(x, 0), default=0)
    p.add_argument("--functions", metavar="FILE",
                   help="JSON list [{\"start\":addr,\"end\":addr}, ...]")
    p.add_argument("--auto-functions", metavar="ELF",
                   help="Auto-detect function boundaries from the given SPU "
                        "ELF using find_spu_functions.py (entry + brsl/brasl "
                        "targets + STT_FUNC symbols). When set, .text is "
                        "read from this ELF and the positional <input> arg "
                        "is ignored.")
    p.add_argument("--trace", action="store_true",
                   help="Emit spu_trace_pc/spu_trace_rt around each instruction "
                        "for §3 diff-vs-RPCS3 validation. Output goes to stderr "
                        "unless spu_trace_init(path) is called by the harness.")
    args = p.parse_args()

    if args.auto_functions:
        from find_spu_functions import detect_functions, parse_elf, pick_text
        with open(args.auto_functions, "rb") as f:
            elf_buf = f.read()
        funcs, (text_off, base, size) = detect_functions(elf_buf)
        data = elf_buf[text_off:text_off + size]
        if args.base != 0:
            base = args.base  # caller override
        bounds = funcs
    else:
        with open(args.input, "rb") as f:
            data = f.read()
        data = data[args.offset:]
        if args.length:
            data = data[:args.length]
        base = args.base

        if args.functions:
            with open(args.functions) as f:
                flist = json.load(f)
            bounds = [(int(str(e["start"]), 0), int(str(e["end"]), 0))
                      for e in flist]
        else:
            # No boundary info: treat the whole image as one function.
            bounds = [(base, base + len(data))]

    insns = disassemble_spu(data, base)

    lifter = SPULifter(trace=args.trace)
    for s, e in bounds:
        lifter.lift_function(insns, s, e)

    os.makedirs(args.output, exist_ok=True)
    hp = os.path.join(args.output, args.header_name)
    sp = os.path.join(args.output, args.source_name)
    with open(hp, "w") as f:
        f.write(lifter.emit_header())
    with open(sp, "w") as f:
        f.write(lifter.emit_source())

    print(f"Wrote {hp}")
    print(f"Wrote {sp}")
    print(f"  {len(lifter.functions)} function(s) lifted")
    print(f"  {len(lifter.call_targets)} call target(s)")
    if lifter.unsupported:
        total = sum(lifter.unsupported.values())
        print(f"  {total} unsupported instruction(s) across "
              f"{len(lifter.unsupported)} mnemonic(s):")
        for mn, n in sorted(lifter.unsupported.items(), key=lambda kv: -kv[1]):
            print(f"      {mn:<10s} {n}")


if __name__ == "__main__":
    main()
