/*
 * ps3recomp game project -- entry point template
 *
 * This file initializes the ps3recomp runtime (memory subsystem, thread
 * manager, HLE module tables), loads the recompiled function table, creates
 * the main PPU thread, and enters the game's original main function.
 *
 * Copy this template into your game project and customize as needed.
 */

#include <cstdio>
#include <cstdlib>
#include <cstring>

#include "ps3emu/ps3types.h"
#include "ps3emu/error_codes.h"

/* ---------------------------------------------------------------------------
 * Forward declarations for runtime subsystems
 *
 * These are provided by the ps3recomp runtime library.  In a real build
 * the headers would be included; this template keeps it self-contained.
 * -----------------------------------------------------------------------*/

/* Memory subsystem */
namespace ps3::memory {
    bool init(size_t main_ram_size);
    void shutdown();
}

/* Thread subsystem */
namespace ps3::thread {
    bool init(int max_threads);
    void shutdown();
    uint64_t create_main_thread(void (*entry)(uint64_t), uint64_t arg,
                                uint32_t stack_size, const char* name);
    void join_thread(uint64_t id);
}

/* Module / NID subsystem */
namespace ps3::modules {
    bool init();
    void shutdown();
    void register_builtin_modules();
}

/* Recompiled function table -- generated by the recompiler tool */
struct RecompiledFunc {
    uint32_t    guest_addr;
    void      (*host_func)(void* ctx);
};

extern const RecompiledFunc g_recompiled_funcs[];
extern const size_t         g_recompiled_func_count;

/* The game's recompiled main function */
extern void recomp_game_main(void* ctx);

/* ---------------------------------------------------------------------------
 * Configuration
 * -----------------------------------------------------------------------*/

static constexpr size_t   MAIN_RAM_SIZE    = 256ULL * 1024 * 1024;   /* 256 MB */
static constexpr int      MAX_PPU_THREADS  = 64;
static constexpr uint32_t MAIN_STACK_SIZE  = 1 * 1024 * 1024;       /* 1 MB */

/* ---------------------------------------------------------------------------
 * Main
 * -----------------------------------------------------------------------*/

int main(int argc, char* argv[])
{
    printf("=== ps3recomp game runner ===\n");
    printf("Initializing runtime...\n");

    /* 1. Initialize memory subsystem -- allocates the guest address space. */
    if (!ps3::memory::init(MAIN_RAM_SIZE)) {
        fprintf(stderr, "ERROR: Failed to initialize memory subsystem\n");
        return 1;
    }

    /* 2. Initialize thread manager. */
    if (!ps3::thread::init(MAX_PPU_THREADS)) {
        fprintf(stderr, "ERROR: Failed to initialize thread subsystem\n");
        ps3::memory::shutdown();
        return 1;
    }

    /* 3. Initialize HLE module tables (cellSysmodule, cellFs, etc.). */
    if (!ps3::modules::init()) {
        fprintf(stderr, "ERROR: Failed to initialize module subsystem\n");
        ps3::thread::shutdown();
        ps3::memory::shutdown();
        return 1;
    }
    ps3::modules::register_builtin_modules();

    /* 4. Load recompiled function table. */
    printf("Loaded %zu recompiled functions\n",
           g_recompiled_func_count);

    /* 5. Create the main PPU thread and enter the game's main(). */
    printf("Creating main PPU thread...\n");

    auto main_entry = [](uint64_t arg) {
        (void)arg;
        /*
         * Call the recompiled game main.  The 'ctx' parameter is the
         * PPU execution context (registers, condition codes, etc.)
         * allocated by the thread manager.
         */
        recomp_game_main(nullptr);
    };

    uint64_t main_tid = ps3::thread::create_main_thread(
        main_entry, 0, MAIN_STACK_SIZE, "main_ppu_thread");

    printf("Main thread ID: %llu -- entering game\n",
           (unsigned long long)main_tid);

    /* 6. Wait for the main thread to finish. */
    ps3::thread::join_thread(main_tid);

    /* 7. Cleanup. */
    printf("Game exited. Shutting down...\n");
    ps3::modules::shutdown();
    ps3::thread::shutdown();
    ps3::memory::shutdown();

    return 0;
}
