#!/usr/bin/env python3
"""Lift single SPU instruction words with tools/spu_lifter.py and emit them as C functions for the
differential test (spu_interp_diff_test.c, --lifted mode).

usage: gen_lifted_cases.py cases.txt > lifted_cases.inc
cases.txt: one "<insn hex> <pc hex>" per line (produced by `spu_interp_diff_test --emit-cases`).
Each case i becomes `static void lc_<i>(spu_context* ctx)` holding exactly what the lifter emits for that word
at that pc (via lift_function over a one-instruction function, so labels / fall-through chaining are the real
ones), plus stubs for the lifted-function symbols it references.
"""
import os, re, sys
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "..", "..", "tools"))
import spu_lifter as L
from spu_disasm import spu_decode

out = []
fns = []
for i, line in enumerate(open(sys.argv[1])):
    f = line.split()
    if len(f) < 2:
        continue
    insn, pc = int(f[0], 16), int(f[1], 16)
    lf = L.SPULifter(prefix=f"c{i}_")
    lf.func_starts = {pc + 4}
    d = spu_decode(insn, pc)
    func = lf.lift_function([d], pc, pc + 4)
    body = "\n".join(func.body_lines)
    refs = set(re.findall(rf"(c{i}_spu_func_([0-9A-Fa-f]{{8}}))", body))
    for name, tgt in sorted(refs):
        if name == func.name:
            continue
        out.append(f"static void {name}(spu_context* ctx);")
    for name, tgt in sorted(refs):
        if name == func.name:
            continue
        out.append(f"static void {name}(spu_context* ctx) {{ ctx->pc = 0x{tgt}u; g_lc_called = 1; g_lc_target = 0x{tgt}u; }}")
    out.append(f"static void {func.name}(spu_context* ctx) {{")
    out.extend(body.split("\n"))
    out.append("}")
    fns.append((insn, pc, func.name))
print("/* GENERATED by gen_lifted_cases.py -- lifted single-instruction functions */")
print("\n".join(out))
print("static const struct { uint32_t insn, pc; void (*fn)(spu_context*); } g_lc_cases[] = {")
for insn, pc, name in fns:
    print(f"    {{ 0x{insn:08X}u, 0x{pc:X}u, {name} }},")
print("};")
print(f"#define LC_NCASES {len(fns)}")
