/* spu_interp_diff_test.c -- bit-exact differential test of the SPU interpreter (and, optionally,
 * the SPU lifter's emitted C) against RPCS3's own SPU interpreter.
 *
 * ORACLE: rpcs3_oracle/ compiles rpcs3/rpcs3/Emu/Cell/SPUInterpreter.cpp's per-instruction
 * functions unmodified (see rpcs3_oracle/extract.py) against a stub spu_thread, decoded with
 * RPCS3's own spu_decoder. Integer/logical/shift/shuffle/memory/branch/channel ops and
 * FREST/FRSQEST/FI are RPCS3's live ("fast") interpreter functions; the floating-point
 * arithmetic/compare/convert and double-precision ops are RPCS3's spu_interpreter_precise::*
 * implementations (the exact-semantics float path: round-toward-zero, denormal flush, extended
 * range). That block is `#if 0` dead code in this RPCS3 snapshot; extract.py enables it.
 * FI is a port of the SPU LLVM recompiler's spu_fi intrinsic (the interpreter's FI is a TODO).
 * Ops RPCS3 does not implement (dfceq/dfcgt/dfcmeq/dfcmgt) fall back to the hand-written ISA
 * reference below (ref_exec); so does dftsv (RPCS3 stubs it as fatal), checked against the Cell SPU ISA.
 * --audit compares that hand-written reference with RPCS3 itself (they agree on every integer op;
 * they differ on float/double, where the hand reference is plain IEEE).
 * Known RPCS3 precise-path quirk compensated for: CSFLT/CUFLT of a zero lane with i8 > 155 returns
 * a nonzero float there; the test expects 0 (see one_trial).
 *
 * Coverage: for every opcode, ALL values of every immediate field (i7/i8/i10/i16/i18), 81
 * rt/ra/rb/rc aliasing patterns (3^4 over three registers) plus fully random register fields,
 * and random + special-valued operands (ints: 0,-1,0x80000000,0x7FFFFFFF,byte patterns; floats:
 * +-0, denormals, +-inf, NaN, max/min normal, extended range, values around 2^31/2^32).
 * Compared bit-exactly: all 128 registers, the quadword touched in LS, next pc, halt/stop state,
 * channel number/operand routing.
 *
 * LIFTED MODE: build_diff_test.sh samples instruction words (--emit-cases), lifts each with
 * tools/spu_lifter.py (gen_lifted_cases.py), compiles the emitted C into a second binary and runs
 * it against the same oracle (`spu_lifted_diff_test --lifted`).
 *
 * Build/run:  ./build_diff_test.sh [--run [-- args]]     (needs the local rpcs3 tree, RPCS3_SRC=...)
 *   build_diff/spu_interp_diff_test [scale] [seed] [--audit] [--op NAME]   interpreter vs RPCS3
 *   build_diff/spu_lifted_diff_test --lifted [scale] [seed]                 lifted C vs RPCS3
 *   CASE_SCALE=N ./build_diff_test.sh   more lifted instruction words per op (default ~21K cases)
 */
#include "../spu_interp.c"   /* spu_step / spu_decode1 are static */
#undef A
#undef B
#undef T
#undef I
#undef DST
#undef DSTC
#undef PREF
#include <assert.h>
#include <stdint.h>
#include <string.h>
#include <math.h>
#include "spu_optab.h"           /* generated by rpcs3_oracle/extract.py */
#include "oracle.h"

/* ---- stubs for the runtime the interpreter links against ---- */
static uint32_t g_ch_n, g_ch_last; static u128 g_ch_val; static uint32_t g_ch_cnt;
u128 spu_rdch(spu_context* c, uint32_t ch) { (void)c; g_ch_last = ch; g_ch_n++; return g_ch_val; }
void spu_wrch(spu_context* c, uint32_t ch, u128 v) { (void)c; g_ch_last = ch; g_ch_n++; g_ch_val = v; }
uint32_t spu_rchcnt(spu_context* c, uint32_t ch) { (void)c; g_ch_last = ch; g_ch_n++; return g_ch_cnt; }
int g_spu_ls_watch_n, g_spu_ls_probe, g_wws_read_probe, g_wws_code_probe, g_spu_smc_watch, g_spu_ls_dbg;
spu_lifted_fn spu_lifted_lookup(const spu_context* c, uint32_t a) { (void)c;(void)a; return 0; }
int (*g_spu_lv2_stop_hook)(spu_context*) = 0;   /* no lv2: stops end the step */
void spu_spurs_taskset_syscall(spu_context* c) { (void)c; }
void spu_trace_pc(spu_context* c, uint32_t pc) { (void)c; (void)pc; }
/* SPU_DIFF_SHOW=N: print up to N mismatches per op (default 3). */
static int show_limit(void) { static int n = -1; if (n < 0) { const char* e = getenv("SPU_DIFF_SHOW"); n = e ? atoi(e) : 3; } return n; }
uint8_t* vm_base = 0;   /* SPU_INTERP_XFER_LOG reads guest memory; never armed here */
void spu_ls_watch_slow(const spu_context* c, uint32_t l, int w, const uint8_t* p, uint32_t pc, uint32_t lr) { (void)c;(void)l;(void)w;(void)p;(void)pc;(void)lr; }

enum { R_UNK = 0,
#define X(m, v, n) R_##n,
SPU_OPTAB(X)
#undef X
  R_COUNT };
static const char* const r_name[R_COUNT] = { "?",
#define X(m, v, n) #n,
SPU_OPTAB(X)
#undef X
};
static const struct { int magn; uint32_t val; int op; } r_tab[] = {
#define X(m, v, n) { m, v, R_##n },
SPU_OPTAB(X)
#undef X
};
#define R_NTAB ((int)(sizeof r_tab / sizeof r_tab[0]))

static int ref_decode(uint32_t insn) {
    uint32_t p = insn >> 21; int op = R_UNK;
    for (int i = 0; i < R_NTAB; i++) if ((p >> r_tab[i].magn) == r_tab[i].val) op = r_tab[i].op;
    return op;
}

/* ---- big-endian quadword model ---- */
typedef struct { uint8_t b[16]; } Q;
typedef unsigned __int128 u128b;
static uint32_t qw(const Q* q, int i) { return (uint32_t)q->b[4*i]<<24 | q->b[4*i+1]<<16 | q->b[4*i+2]<<8 | q->b[4*i+3]; }
static void sw(Q* q, int i, uint32_t v) { q->b[4*i]=v>>24; q->b[4*i+1]=v>>16; q->b[4*i+2]=v>>8; q->b[4*i+3]=v; }
static uint16_t qh(const Q* q, int i) { return (uint16_t)(q->b[2*i]<<8 | q->b[2*i+1]); }
static void sh_(Q* q, int i, uint16_t v) { q->b[2*i]=v>>8; q->b[2*i+1]=v; }
static uint64_t qd(const Q* q, int i) { return (uint64_t)qw(q,2*i)<<32 | qw(q,2*i+1); }
static void sd(Q* q, int i, uint64_t v) { sw(q,2*i,(uint32_t)(v>>32)); sw(q,2*i+1,(uint32_t)v); }
static Q q_of(u128 v) { Q q; for (int i = 0; i < 4; i++) sw(&q, i, v._u32[i]); return q; }
static u128b q128(const Q* q) { u128b r = 0; for (int i = 0; i < 16; i++) r = (r << 8) | q->b[i]; return r; }
static Q of128(u128b v) { Q q; for (int i = 15; i >= 0; i--) { q.b[i] = (uint8_t)v; v >>= 8; } return q; }
static Q splat32(uint32_t v) { Q q; for (int i = 0; i < 4; i++) sw(&q, i, v); return q; }
static float f_of(uint32_t u) { float f; memcpy(&f, &u, 4); return f; }
static uint32_t u_of(float f) { uint32_t u; memcpy(&u, &f, 4); return u; }

/* ---- reference result ---- */
typedef struct {
    int dest; Q val;                 /* destination reg (-1 none) */
    uint32_t next;                   /* next pc */
    int halt, stop; uint32_t stop_code;
    int st; uint32_t st_addr; Q st_val;
    int ch_op; uint32_t ch_no;       /* 1 rdch, 2 wrch, 3 rchcnt */
    int fuzzy;                       /* float result: allow 1 ulp per word */
    int fuzzd;                       /* double result */
} Ref;

static int32_t sx_(uint32_t v, int bits) { uint32_t m = 1u << (bits - 1); return (int32_t)((v ^ m) - m); }
#define LSM 0x3FFFFu

/* ref_exec: regs = original register file (Q computed on demand), ls = pristine LS */
static Ref ref_exec(int op, uint32_t insn, uint32_t pc, const u128* regs, const uint8_t* ls, uint32_t srr0, uint32_t evt) {
    Ref R; memset(&R, 0, sizeof R); R.dest = -1; R.next = (pc + 4) & LSM;
    int rt = insn & 0x7F, ra = (insn >> 7) & 0x7F, rb = (insn >> 14) & 0x7F;
    int rc = insn & 0x7F, rt4 = (insn >> 21) & 0x7F;
    uint32_t i7 = (insn >> 14) & 0x7F, i8 = (insn >> 14) & 0xFF;
    int32_t si10 = sx_((insn >> 14) & 0x3FF, 10), si16 = sx_((insn >> 7) & 0xFFFF, 16);
    uint32_t i16 = (insn >> 7) & 0xFFFF, i18 = (insn >> 7) & 0x3FFFF;
    Q A = q_of(regs[ra]), B = q_of(regs[rb]), T = q_of(regs[rt]);   /* T: rt as a source (also rc in RRR) */
    Q C = T; (void)rc;
    Q r; memset(&r, 0, sizeof r);
    int dest = rt;
    uint32_t aw0 = qw(&A, 0), bw0 = qw(&B, 0);
    int i;
#define W(q,i) qw(&(q),i)
#define LANE4(expr) for (i = 0; i < 4; i++) { uint32_t a = W(A,i), b = W(B,i), t = W(T,i); (void)a;(void)b;(void)t; sw(&r, i, (uint32_t)(expr)); }
#define LANE8(expr) for (i = 0; i < 8; i++) { uint16_t a = qh(&A,i), b = qh(&B,i); (void)a;(void)b; sh_(&r, i, (uint16_t)(expr)); }
#define LANE16(expr) for (i = 0; i < 16; i++) { uint8_t a = A.b[i], b = B.b[i]; (void)a;(void)b; r.b[i] = (uint8_t)(expr); }
#define LANE16I(expr) for (i = 0; i < 16; i++) { uint8_t a = A.b[i]; (void)a; r.b[i] = (uint8_t)(expr); }
    switch (op) {
    case R_STOP: R.stop = 1; R.stop_code = insn & 0x3FFF; dest = -1; break;
    case R_STOPD: R.stop = 1; R.stop_code = 0x3FFF; dest = -1; break;   /* stopd has no code field; RPCS3 reports 0x3FFF */
    case R_LNOP: case R_NOP: case R_SYNC: case R_DSYNC: case R_MTSPR: case R_HBR: case R_HBRA: case R_HBRR:
    case R_FSCRWR: dest = -1; break;
    case R_MFSPR: case R_FSCRRD: break;                         /* reads as zero */
    case R_RDCH: R.ch_op = 1; R.ch_no = ra; break;
    case R_WRCH: R.ch_op = 2; R.ch_no = ra; dest = -1; break;
    case R_RCHCNT: R.ch_op = 3; R.ch_no = ra; break;
    /* integer */
    case R_A: LANE4(a + b); break;
    case R_SF: LANE4(b - a); break;
    case R_AH: LANE8(a + b); break;
    case R_SFH: LANE8(b - a); break;
    case R_AI: LANE4(a + (uint32_t)si10); break;
    case R_AHI: LANE8(a + (uint16_t)si10); break;
    case R_SFI: LANE4((uint32_t)si10 - a); break;
    case R_SFHI: LANE8((uint16_t)si10 - a); break;
    case R_ADDX: LANE4(a + b + (t & 1)); break;
    case R_SFX: LANE4(b - a - 1 + (t & 1)); break;
    case R_CG: LANE4(((uint64_t)a + b) >> 32); break;
    case R_CGX: LANE4(((uint64_t)a + b + (t & 1)) >> 32); break;
    case R_BG: LANE4(b >= a ? 1 : 0); break;
    case R_BGX: LANE4(((uint64_t)b + (uint32_t)~a + (t & 1)) >> 32); break;
    case R_MPY: LANE4((int32_t)(int16_t)a * (int32_t)(int16_t)b); break;
    case R_MPYU: LANE4((uint32_t)(a & 0xFFFF) * (b & 0xFFFF)); break;
    case R_MPYH: LANE4(((int32_t)(int16_t)(a >> 16) * (int32_t)(int16_t)b) * 65536); break;
    case R_MPYHH: LANE4((int32_t)(int16_t)(a >> 16) * (int32_t)(int16_t)(b >> 16)); break;
    case R_MPYHHU: LANE4((a >> 16) * (b >> 16)); break;
    case R_MPYS: LANE4((int32_t)(int16_t)(((int32_t)(int16_t)a * (int32_t)(int16_t)b) >> 16)); break;
    case R_MPYHHA: LANE4(t + (int32_t)(int16_t)(a >> 16) * (int32_t)(int16_t)(b >> 16)); break;
    case R_MPYHHAU: LANE4(t + (a >> 16) * (b >> 16)); break;
    case R_MPYI: LANE4((int32_t)(int16_t)a * si10); break;
    case R_MPYUI: LANE4((a & 0xFFFF) * (uint16_t)si10); break;
    case R_MPYA: { dest = rt4; Q c = q_of(regs[rc]); for (i = 0; i < 4; i++) { uint32_t a = W(A,i), b = W(B,i);
            sw(&r, i, (uint32_t)((int32_t)(int16_t)a * (int32_t)(int16_t)b) + W(c,i)); } break; }
    case R_CLZ: LANE4(a ? __builtin_clz(a) : 32); break;
    case R_CNTB: LANE16I(__builtin_popcount(a)); break;
    case R_XSBH: LANE8((int16_t)(int8_t)(qh(&A,i) & 0xFF)); break;
    case R_XSHW: LANE4((int32_t)(int16_t)(a & 0xFFFF)); break;
    case R_XSWD: for (i = 0; i < 2; i++) sd(&r, i, (uint64_t)(int64_t)(int32_t)qw(&A, 2*i+1)); break;
    case R_ORX: sw(&r, 0, W(A,0)|W(A,1)|W(A,2)|W(A,3)); break;
    case R_ABSDB: LANE16(a > b ? a - b : b - a); break;
    case R_AVGB: LANE16(((unsigned)a + b + 1) >> 1); break;
    case R_SUMB: for (i = 0; i < 4; i++) { uint32_t sa = 0, sb = 0; for (int k = 0; k < 4; k++) { sa += A.b[4*i+k]; sb += B.b[4*i+k]; }
            sh_(&r, 2*i, (uint16_t)sb); sh_(&r, 2*i+1, (uint16_t)sa); } break;
    /* logical */
    case R_AND: LANE16(a & b); break;
    case R_OR: LANE16(a | b); break;
    case R_XOR: LANE16(a ^ b); break;
    case R_NAND: LANE16(~(a & b)); break;
    case R_NOR: LANE16(~(a | b)); break;
    case R_ANDC: LANE16(a & ~b); break;
    case R_ORC: LANE16(a | ~b); break;
    case R_EQV: LANE16(~(a ^ b)); break;
    case R_ANDI: LANE4(a & (uint32_t)si10); break;
    case R_ORI: LANE4(a | (uint32_t)si10); break;
    case R_XORI: LANE4(a ^ (uint32_t)si10); break;
    case R_ANDHI: LANE8(a & (uint16_t)si10); break;
    case R_ORHI: LANE8(a | (uint16_t)si10); break;
    case R_XORHI: LANE8(a ^ (uint16_t)si10); break;
    case R_ANDBI: LANE16I(a & (uint8_t)si10); break;
    case R_ORBI: LANE16I(a | (uint8_t)si10); break;
    case R_XORBI: LANE16I(a ^ (uint8_t)si10); break;
    case R_SELB: { dest = rt4; Q c = q_of(regs[rc]); for (i = 0; i < 16; i++) r.b[i] = (c.b[i] & B.b[i]) | (~c.b[i] & A.b[i]); break; }
    case R_SHUFB: { dest = rt4; Q c = q_of(regs[rc]);
        for (i = 0; i < 16; i++) { uint8_t s = c.b[i], v;
            if ((s & 0xC0) == 0x80) v = 0; else if ((s & 0xE0) == 0xC0) v = 0xFF; else if ((s & 0xE0) == 0xE0) v = 0x80;
            else { int k = s & 0x1F; v = k < 16 ? A.b[k] : B.b[k - 16]; }
            r.b[i] = v; } break; }
    /* compares */
    case R_CEQ: LANE4(a == b ? ~0u : 0); break;
    case R_CEQH: LANE8(a == b ? 0xFFFF : 0); break;
    case R_CEQB: LANE16(a == b ? 0xFF : 0); break;
    case R_CEQI: LANE4(a == (uint32_t)si10 ? ~0u : 0); break;
    case R_CEQHI: LANE8(a == (uint16_t)si10 ? 0xFFFF : 0); break;
    case R_CEQBI: LANE16I(a == (uint8_t)si10 ? 0xFF : 0); break;
    case R_CGT: LANE4((int32_t)a > (int32_t)b ? ~0u : 0); break;
    case R_CGTH: LANE8((int16_t)a > (int16_t)b ? 0xFFFF : 0); break;
    case R_CGTB: LANE16((int8_t)a > (int8_t)b ? 0xFF : 0); break;
    case R_CGTI: LANE4((int32_t)a > si10 ? ~0u : 0); break;
    case R_CGTHI: LANE8((int16_t)a > (int16_t)si10 ? 0xFFFF : 0); break;
    case R_CGTBI: LANE16I((int8_t)a > (int8_t)si10 ? 0xFF : 0); break;
    case R_CLGT: LANE4(a > b ? ~0u : 0); break;
    case R_CLGTH: LANE8(a > b ? 0xFFFF : 0); break;
    case R_CLGTB: LANE16(a > b ? 0xFF : 0); break;
    case R_CLGTI: LANE4(a > (uint32_t)si10 ? ~0u : 0); break;
    case R_CLGTHI: LANE8(a > (uint16_t)si10 ? 0xFFFF : 0); break;
    case R_CLGTBI: LANE16I(a > (uint8_t)si10 ? 0xFF : 0); break;
    case R_HEQ: dest = -1; R.halt = (int32_t)aw0 == (int32_t)bw0; break;
    case R_HEQI: dest = -1; R.halt = (int32_t)aw0 == si10; break;
    case R_HGT: dest = -1; R.halt = (int32_t)aw0 > (int32_t)bw0; break;
    case R_HGTI: dest = -1; R.halt = (int32_t)aw0 > si10; break;
    case R_HLGT: dest = -1; R.halt = aw0 > bw0; break;
    case R_HLGTI: dest = -1; R.halt = aw0 > (uint32_t)si10; break;
    /* shifts / rotates */
    case R_SHL: LANE4((b & 0x3F) > 31 ? 0 : a << (b & 0x3F)); break;
    case R_SHLI: LANE4((i7 & 0x3F) > 31 ? 0 : a << (i7 & 0x3F)); break;
    case R_ROT: LANE4((a << (b & 31)) | (uint32_t)((uint64_t)a >> (32 - (b & 31)) & 0xFFFFFFFFu)); break;
    case R_ROTI: LANE4((a << (i7 & 31)) | (uint32_t)((uint64_t)a >> (32 - (i7 & 31)) & 0xFFFFFFFFu)); break;
    case R_ROTM: LANE4(((0u - b) & 0x3F) > 31 ? 0 : a >> ((0u - b) & 0x3F)); break;
    case R_ROTMI: LANE4(((0u - i7) & 0x3F) > 31 ? 0 : a >> ((0u - i7) & 0x3F)); break;
    case R_ROTMA: LANE4(((0u - b) & 0x3F) > 31 ? (uint32_t)((int32_t)a >> 31) : (uint32_t)((int32_t)a >> ((0u - b) & 0x3F))); break;
    case R_ROTMAI: LANE4(((0u - i7) & 0x3F) > 31 ? (uint32_t)((int32_t)a >> 31) : (uint32_t)((int32_t)a >> ((0u - i7) & 0x3F))); break;
    case R_SHLH: LANE8((b & 0x1F) > 15 ? 0 : a << (b & 0x1F)); break;
    case R_SHLHI: LANE8((i7 & 0x1F) > 15 ? 0 : a << (i7 & 0x1F)); break;
    case R_ROTH: LANE8(((uint32_t)a << (b & 15)) | ((uint32_t)a >> (16 - (b & 15)))); break;
    case R_ROTHI: LANE8(((uint32_t)a << (i7 & 15)) | ((uint32_t)a >> (16 - (i7 & 15)))); break;
    case R_ROTHM: LANE8(((0u - b) & 0x1F) > 15 ? 0 : a >> ((0u - b) & 0x1F)); break;
    case R_ROTHMI: LANE8(((0u - i7) & 0x1F) > 15 ? 0 : a >> ((0u - i7) & 0x1F)); break;
    case R_ROTMAH: LANE8(((0u - b) & 0x1F) > 15 ? (int16_t)a >> 15 : (int16_t)a >> ((0u - b) & 0x1F)); break;
    case R_ROTMAHI: LANE8(((0u - i7) & 0x1F) > 15 ? (int16_t)a >> 15 : (int16_t)a >> ((0u - i7) & 0x1F)); break;
    case R_SHLQBI: case R_SHLQBII: { unsigned n = (op == R_SHLQBI ? bw0 : i7) & 7; r = of128(q128(&A) << n); break; }
    case R_ROTQBI: case R_ROTQBII: { unsigned n = (op == R_ROTQBI ? bw0 : i7) & 7; u128b v = q128(&A); r = of128(n ? (v << n) | (v >> (128 - n)) : v); break; }
    case R_ROTQMBI: case R_ROTQMBII: { unsigned n = (0u - (op == R_ROTQMBI ? bw0 : i7)) & 7; r = of128(q128(&A) >> n); break; }
    case R_SHLQBY: case R_SHLQBYI: case R_SHLQBYBI: { unsigned n = op == R_SHLQBY ? (bw0 & 0x1F) : op == R_SHLQBYI ? (i7 & 0x1F) : ((bw0 >> 3) & 0x1F);
        for (i = 0; i < 16; i++) r.b[i] = (i + n < 16) ? A.b[i + n] : 0; break; }
    case R_ROTQBY: case R_ROTQBYI: case R_ROTQBYBI: { unsigned n = op == R_ROTQBY ? (bw0 & 0xF) : op == R_ROTQBYI ? (i7 & 0xF) : ((bw0 >> 3) & 0xF);
        for (i = 0; i < 16; i++) r.b[i] = A.b[(i + n) & 15]; break; }
    case R_ROTQMBY: case R_ROTQMBYI: case R_ROTQMBYBI: { unsigned n = op == R_ROTQMBY ? ((0u - bw0) & 0x1F) : op == R_ROTQMBYI ? ((0u - i7) & 0x1F) : ((0u - (bw0 >> 3)) & 0x1F);
        for (i = 0; i < 16; i++) r.b[i] = (i >= (int)n && n < 16) ? A.b[i - n] : 0; break; }
    /* masks / gathers */
    case R_FSM: { uint32_t v = aw0; for (i = 0; i < 4; i++) sw(&r, i, ((v >> (3 - i)) & 1) ? ~0u : 0); break; }
    case R_FSMH: { uint32_t v = aw0; for (i = 0; i < 8; i++) sh_(&r, i, ((v >> (7 - i)) & 1) ? 0xFFFF : 0); break; }
    case R_FSMB: { uint32_t v = aw0; for (i = 0; i < 16; i++) r.b[i] = ((v >> (15 - i)) & 1) ? 0xFF : 0; break; }
    case R_FSMBI: for (i = 0; i < 16; i++) r.b[i] = ((i16 >> (15 - i)) & 1) ? 0xFF : 0; break;
    case R_GB: { uint32_t v = 0; for (i = 0; i < 4; i++) v |= (W(A,i) & 1) << (3 - i); sw(&r, 0, v); break; }
    case R_GBH: { uint32_t v = 0; for (i = 0; i < 8; i++) v |= (qh(&A,i) & 1u) << (7 - i); sw(&r, 0, v); break; }
    case R_GBB: { uint32_t v = 0; for (i = 0; i < 16; i++) v |= (A.b[i] & 1u) << (15 - i); sw(&r, 0, v); break; }
    case R_CBD: case R_CBX: case R_CHD: case R_CHX: case R_CWD: case R_CWX: case R_CDD: case R_CDX: {
        uint32_t t = aw0 + ((op==R_CBD||op==R_CHD||op==R_CWD||op==R_CDD) ? (uint32_t)sx_(i7,7) : bw0);
        int sz = (op==R_CBD||op==R_CBX) ? 1 : (op==R_CHD||op==R_CHX) ? 2 : (op==R_CWD||op==R_CWX) ? 4 : 8;
        for (i = 0; i < 16; i++) r.b[i] = 0x10 + i;
        int p = t & 15 & ~(sz - 1);
        if (sz == 1) r.b[p] = 3;
        else if (sz == 2) { r.b[p] = 2; r.b[p+1] = 3; }
        else for (i = 0; i < sz; i++) r.b[p+i] = i;
        break; }
    /* immediates */
    case R_IL: r = splat32((uint32_t)si16); break;
    case R_ILH: for (i = 0; i < 8; i++) sh_(&r, i, (uint16_t)i16); break;
    case R_ILHU: r = splat32(i16 << 16); break;
    case R_ILA: r = splat32(i18); break;
    case R_IOHL: LANE4(t | i16); break;
    /* memory */
    case R_LQD: case R_LQX: case R_LQA: case R_LQR: {
        uint32_t ad = op == R_LQD ? (aw0 + (uint32_t)(si10 * 16)) : op == R_LQX ? aw0 + bw0
                    : op == R_LQA ? (uint32_t)(si16 * 4) : pc + (uint32_t)(si16 * 4);
        ad &= 0x3FFF0; memcpy(r.b, ls + ad, 16); R.st = 1; R.st_addr = ad; memcpy(R.st_val.b, r.b, 16); break; }
    case R_STQD: case R_STQX: case R_STQA: case R_STQR: {
        uint32_t ad = op == R_STQD ? (aw0 + (uint32_t)(si10 * 16)) : op == R_STQX ? aw0 + bw0
                    : op == R_STQA ? (uint32_t)(si16 * 4) : pc + (uint32_t)(si16 * 4);
        R.st = 1; R.st_addr = ad & 0x3FFF0; R.st_val = T; dest = -1; break; }
    /* branches */
    case R_BR: R.next = (pc + (uint32_t)(si16 * 4)) & 0x3FFFC; dest = -1; break;
    case R_BRA: R.next = (uint32_t)(si16 * 4) & 0x3FFFC; dest = -1; break;
    case R_BRSL: R.next = (pc + (uint32_t)(si16 * 4)) & 0x3FFFC; sw(&r, 0, (pc + 4) & 0x3FFFC); break;
    case R_BRASL: R.next = (uint32_t)(si16 * 4) & 0x3FFFC; sw(&r, 0, (pc + 4) & 0x3FFFC); break;
    case R_BRZ: dest = -1; if (W(T,0) == 0) R.next = (pc + (uint32_t)(si16 * 4)) & 0x3FFFC; break;
    case R_BRNZ: dest = -1; if (W(T,0) != 0) R.next = (pc + (uint32_t)(si16 * 4)) & 0x3FFFC; break;
    case R_BRHZ: dest = -1; if ((W(T,0) & 0xFFFF) == 0) R.next = (pc + (uint32_t)(si16 * 4)) & 0x3FFFC; break;
    case R_BRHNZ: dest = -1; if ((W(T,0) & 0xFFFF) != 0) R.next = (pc + (uint32_t)(si16 * 4)) & 0x3FFFC; break;
    case R_BI: R.next = aw0 & 0x3FFFC; dest = -1; break;
    case R_BISL: R.next = aw0 & 0x3FFFC; sw(&r, 0, (pc + 4) & 0x3FFFC); break;
    case R_IRET: R.next = srr0 & 0x3FFFC; dest = -1; break;
    case R_BISLED: sw(&r, 0, (pc + 4) & 0x3FFFC); if (evt) R.next = aw0 & 0x3FFFC; break;
    case R_BIZ: dest = -1; if (W(T,0) == 0) R.next = aw0 & 0x3FFFC; break;
    case R_BINZ: dest = -1; if (W(T,0) != 0) R.next = aw0 & 0x3FFFC; break;
    case R_BIHZ: dest = -1; if ((W(T,0) & 0xFFFF) == 0) R.next = aw0 & 0x3FFFC; break;
    case R_BIHNZ: dest = -1; if ((W(T,0) & 0xFFFF) != 0) R.next = aw0 & 0x3FFFC; break;
    /* single precision (tame operands; 1-ulp tolerance, see header) */
    case R_FA: R.fuzzy = 1; LANE4(u_of(f_of(a) + f_of(b))); break;
    case R_FS: R.fuzzy = 1; LANE4(u_of(f_of(a) - f_of(b))); break;
    case R_FM: R.fuzzy = 1; LANE4(u_of(f_of(a) * f_of(b))); break;
    case R_FMA: case R_FMS: case R_FNMS: { R.fuzzy = 1; dest = rt4; Q c = q_of(regs[rc]);
        for (i = 0; i < 4; i++) { double x = (double)f_of(W(A,i)) * (double)f_of(W(B,i)), cc = f_of(W(c,i));
            double v = op == R_FMA ? x + cc : op == R_FMS ? x - cc : cc - x; sw(&r, i, u_of((float)v)); } break; }
    case R_FCEQ: LANE4(f_of(a) == f_of(b) ? ~0u : 0); break;
    case R_FCGT: LANE4(f_of(a) > f_of(b) ? ~0u : 0); break;
    case R_FCMEQ: LANE4(fabsf(f_of(a)) == fabsf(f_of(b)) ? ~0u : 0); break;
    case R_FCMGT: LANE4(fabsf(f_of(a)) > fabsf(f_of(b)) ? ~0u : 0); break;
    case R_CFLTS: for (i = 0; i < 4; i++) { double v = trunc((double)f_of(W(A,i)) * ldexp(1.0, 173 - (int)i8));
            sw(&r, i, v >= 2147483648.0 ? 0x7FFFFFFFu : v <= -2147483649.0 ? 0x80000000u : (uint32_t)(int32_t)v); } break;
    case R_CFLTU: for (i = 0; i < 4; i++) { double v = trunc((double)f_of(W(A,i)) * ldexp(1.0, 173 - (int)i8));
            sw(&r, i, v >= 4294967296.0 ? 0xFFFFFFFFu : v <= 0 ? 0 : (uint32_t)v); } break;
    case R_CSFLT: R.fuzzy = 1; for (i = 0; i < 4; i++) sw(&r, i, u_of((float)((double)(int32_t)W(A,i) * ldexp(1.0, (int)i8 - 155)))); break;
    case R_CUFLT: R.fuzzy = 1; for (i = 0; i < 4; i++) sw(&r, i, u_of((float)((double)W(A,i) * ldexp(1.0, (int)i8 - 155)))); break;
    /* double precision (IEEE nearest-even, fused FMA) */
#define DBL(x) ({ uint64_t _u = qd(&x, d_); double _d; memcpy(&_d, &_u, 8); _d; })
#define DSET(v) do { double _v = (v); uint64_t _u; memcpy(&_u, &_v, 8); sd(&r, d_, _u); } while (0)
    case R_DFA: for (int d_ = 0; d_ < 2; d_++) DSET(DBL(A) + DBL(B)); break;
    case R_DFS: for (int d_ = 0; d_ < 2; d_++) DSET(DBL(A) - DBL(B)); break;
    case R_DFM: for (int d_ = 0; d_ < 2; d_++) DSET(DBL(A) * DBL(B)); break;
    case R_DFMA: for (int d_ = 0; d_ < 2; d_++) DSET(fma(DBL(A), DBL(B), DBL(T))); break;
    case R_DFMS: for (int d_ = 0; d_ < 2; d_++) DSET(fma(DBL(A), DBL(B), -DBL(T))); break;
    case R_DFNMS: for (int d_ = 0; d_ < 2; d_++) DSET(fma(-DBL(A), DBL(B), DBL(T))); break;
    case R_DFNMA: for (int d_ = 0; d_ < 2; d_++) DSET(-fma(DBL(A), DBL(B), DBL(T))); break;
    case R_DFCEQ: for (int d_ = 0; d_ < 2; d_++) sd(&r, d_, DBL(A) == DBL(B) ? ~0ull : 0); break;
    case R_DFCGT: for (int d_ = 0; d_ < 2; d_++) sd(&r, d_, DBL(A) > DBL(B) ? ~0ull : 0); break;
    case R_DFCMEQ: for (int d_ = 0; d_ < 2; d_++) sd(&r, d_, fabs(DBL(A)) == fabs(DBL(B)) ? ~0ull : 0); break;
    case R_DFCMGT: for (int d_ = 0; d_ < 2; d_++) sd(&r, d_, fabs(DBL(A)) > fabs(DBL(B)) ? ~0ull : 0); break;
    case R_DFTSV: for (int d_ = 0; d_ < 2; d_++) {     /* Cell SPU ISA dftsv (no RPCS3 impl) */
        uint64_t v = qd(&A, d_), e = (v >> 52) & 0x7FF, f = v & 0xFFFFFFFFFFFFFull; int ng = (int)(v >> 63), t = 0;
        if (e == 0x7FF && f) t |= i7 & 0x40;
        if (e == 0x7FF && !f) t |= i7 & (ng ? 0x10 : 0x20);
        if (e == 0 && !f) t |= i7 & (ng ? 0x04 : 0x08);
        if (e == 0 && f) t |= i7 & (ng ? 0x01 : 0x02);
        sd(&r, d_, t ? ~0ull : 0); } break;
    case R_FESD: for (int d_ = 0; d_ < 2; d_++) DSET((double)f_of(qw(&A, 2*d_))); break;
    case R_FRDS: for (int d_ = 0; d_ < 2; d_++) { uint64_t u = qd(&A, d_); double dd; memcpy(&dd, &u, 8); sw(&r, 2*d_, u_of((float)dd)); } break;
    default: R.next = ~0u; return R;      /* not covered by the reference: caller skips */
    }
    R.dest = dest; R.val = r;
    (void)C;
    return R;
}


/* ---- runtime stubs the lifter's emitted code references (lifted mode) ---- */
/* g_spu_trampoline_fn is a spu_context field now (spu_context.h). */
static uint32_t g_lc_target; static int g_lc_called;
void spu_indirect_branch(spu_context* c) { g_lc_called = 1; g_lc_target = c->pc & 0x3FFFC; }
void spu_stop(spu_context* c) { (void)c; }
void spu_halt(spu_context* c) { (void)c; }
void spu_drain_call(spu_context* c, uint32_t r) { (void)c; (void)r; }
void spu_img_restore(spu_context* c, int32_t sv) { (void)c; (void)sv; }
#ifdef LIFTED_CASES_INC
#include LIFTED_CASES_INC       /* generated by gen_lifted_cases.py: g_lc_cases[], LC_NCASES */
#endif

/* ======================================================================================== */
/* RNG and operand generation                                                               */
/* ======================================================================================== */
static const char* lname(int op, char* buf) { int i = 0; for (const char* s = r_name[op]; *s; s++) buf[i++] = (*s >= 'A' && *s <= 'Z') ? *s + 32 : *s; buf[i] = 0; return buf; }
static uint64_t g_rng = 0x9E3779B97F4A7C15ull;
static uint32_t rnd(void) { g_rng ^= g_rng << 13; g_rng ^= g_rng >> 7; g_rng ^= g_rng << 17; return (uint32_t)(g_rng >> 16); }
static uint64_t rnd64(void) { return (uint64_t)rnd() << 32 | rnd(); }

static uint32_t special_int(void) {
    static const uint32_t sp[] = { 0, ~0u, 0x80000000u, 0x7FFFFFFFu, 1, 0xFFFFu, 0x10000u, 0x8000u, 0xFFFF0000u, 0x7Fu, 0x80u, 0xFFu,
        0x01010101u, 0x80808080u, 0x7F7F7F7Fu, 0xFF00FF00u, 0x00FF00FFu, 0x7FFF7FFFu, 0x80008000u, 0x0000FFFFu };
    switch (rnd() & 3) {
    case 0: return sp[rnd() % (sizeof sp / sizeof sp[0])];
    case 1: return rnd() % 70;
    case 2: return (uint32_t)(0 - (rnd() % 70));
    default: return 1u << (rnd() & 31);
    }
}
static uint32_t int_word(void) {
    switch (rnd() & 3) {
    case 0: return rnd();
    case 1: return special_int();
    case 2: { static const uint8_t bs[] = {0,1,0x7F,0x80,0xFF}; uint32_t v = 0; for (int k = 0; k < 4; k++) v = v << 8 | bs[rnd() % 5]; return v; }
    default: return (rnd() & 0xFFFF) | (special_int() << 16);
    }
}
static uint32_t g_sweep;
static uint32_t float_word(void) {
    if ((rnd() & 7) == 0) { uint32_t w = (g_sweep++ & 0x1FFu) << 23 | (rnd() & 0x7FFFFF); return w; }   /* sweep every sign/exponent
    */
    uint32_t sgn = (rnd() & 1) ? 0x80000000u : 0;
    switch (rnd() % 16) {
    case 0: return sgn;                                             /* +-0 */
    case 1: return sgn | (1 + rnd() % 0x7FFFFF);                    /* denormal */
    case 2: return sgn | 0x7F800000u;                               /* +-inf (extended exp 255) */
    case 3: return sgn | 0x7F800000u | (rnd() & 0x7FFFFF);          /* NaN / extended */
    case 4: return sgn | 0x7F7FFFFFu;                               /* max normal */
    case 5: return sgn | 0x00800000u | ((rnd() & 3) ? 0 : (rnd() & 0x7FFFFF)); /* min normal */
    case 6: { static const uint32_t n[] = { 0x4F000000u, 0x4EFFFFFFu, 0x4F000001u, 0x4F800000u, 0x4F7FFFFFu, 0x4F800001u, 0x4F7FFFFEu, 0x3F800000u, 0x3F000000u, 0x40000000u, 0x7F000000u, 0x00FFFFFFu, 0x7EFFFFFFu };
              return sgn | n[rnd() % (sizeof n / sizeof n[0])]; }
    case 7: case 8: return rnd();                                   /* any bit pattern */
    case 9: return sgn | ((uint32_t)(1 + rnd() % 254) << 23) | (rnd() & 0x7FFFFF);  /* random normal */
    case 10: return sgn | ((uint32_t)(250 + rnd() % 6) << 23) | (rnd() & 0x7FFFFF); /* near-overflow */
    case 11: return sgn | ((uint32_t)(rnd() % 6) << 23) | (rnd() & 0x7FFFFF);       /* near-underflow */
    default: return sgn | ((uint32_t)(110 + rnd() % 31) << 23) | (rnd() & 0x7FFFFF); /* tame */
    }
}
static uint64_t double_word(void) {
    uint64_t sgn = (rnd() & 1) ? 1ull << 63 : 0, m = rnd64() & 0xFFFFFFFFFFFFFull;
    switch (rnd() % 14) {
    case 0: return sgn;
    case 1: return sgn | (m ? m : 1);                               /* denormal */
    case 2: return sgn | 0x7FF0000000000000ull;                     /* inf */
    case 3: return sgn | 0x7FF0000000000000ull | (m ? m : 1);      /* NaN (quiet or signalling) */
    case 4: return sgn | 0x7FEFFFFFFFFFFFFFull;                     /* max normal */
    case 5: return sgn | 0x0010000000000000ull;                     /* min normal */
    case 6: return sgn | 0x3FF0000000000000ull | (rnd() & 1 ? m : 0);
    case 7: return rnd64();
    case 8: return sgn | ((uint64_t)(1 + rnd() % 2046) << 52) | m;  /* random normal */
    case 9: return sgn | ((uint64_t)(2040 + rnd() % 7) << 52) | m;  /* near overflow */
    case 10: return sgn | ((uint64_t)(rnd() % 6) << 52) | m;        /* near underflow */
    default: return sgn | ((uint64_t)(1000 + rnd() % 48) << 52) | m; /* tame */
    }
}
/* operand class of an op: 0 integer, 1 single float, 2 double */
static int op_kind(int op) {
    switch (op) {
    case R_FA: case R_FS: case R_FM: case R_FMA: case R_FMS: case R_FNMS: case R_FCEQ: case R_FCGT: case R_FCMEQ: case R_FCMGT:
    case R_FREST: case R_FRSQEST: case R_FI: case R_CFLTS: case R_CFLTU: case R_FESD: return 1;
    case R_DFA: case R_DFS: case R_DFM: case R_DFMA: case R_DFMS: case R_DFNMS: case R_DFNMA: case R_DFCEQ: case R_DFCGT:
    case R_DFCMEQ: case R_DFCMGT: case R_DFTSV: case R_FRDS: return 2;
    }
    return 0;
}

static spu_context g_ctx;
static u128 g_orig[128];
static uint8_t g_gbe[128][16];
static uint8_t g_ls0[0x40000];     /* pristine LS (never holds the test instruction) */

static void bsw_store(uint8_t* o, const u128* v) { for (int i = 0; i < 4; i++) { uint32_t w = v->_u32[i]; o[4*i] = w >> 24; o[4*i+1] = w >> 16; o[4*i+2] = w >> 8; o[4*i+3] = w; } }
static void set_reg(int r, uint32_t w0, uint32_t w1, uint32_t w2, uint32_t w3) {
    g_orig[r]._u32[0] = w0; g_orig[r]._u32[1] = w1; g_orig[r]._u32[2] = w2; g_orig[r]._u32[3] = w3; bsw_store(g_gbe[r], &g_orig[r]);
}
static void fill_reg(int r, int kind) {
    uint32_t w[4];
    if (kind == 0) for (int i = 0; i < 4; i++) w[i] = int_word();
    else if (kind == 1) for (int i = 0; i < 4; i++) w[i] = float_word();
    else { for (int i = 0; i < 2; i++) { uint64_t d = double_word(); w[2*i] = (uint32_t)(d >> 32); w[2*i+1] = (uint32_t)d; } }
    set_reg(r, w[0], w[1], w[2], w[3]);
}

/* ======================================================================================== */
/* instruction construction                                                                 */
/* ======================================================================================== */
enum { F_NONE, F_I7, F_I8, F_I10, F_I16, F_I18 };
static int op_magn(int op) { for (int i = 0; i < R_NTAB; i++) if (r_tab[i].op == op) return r_tab[i].magn; return -1; }
static int op_imm_kind(int op) {
    switch (op) {
    case R_ROTI: case R_ROTMI: case R_ROTMAI: case R_SHLI: case R_ROTHI: case R_ROTHMI: case R_ROTMAHI: case R_SHLHI:
    case R_CBD: case R_CHD: case R_CWD: case R_CDD: case R_ROTQBII: case R_ROTQMBII: case R_SHLQBII: case R_ROTQBYI: case R_ROTQMBYI: case R_SHLQBYI:
        return F_I7;
    }
    switch (op_magn(op)) { case 1: return F_I8; case 2: return F_I16; case 3: return F_I10; case 4: return F_I18; }
    return F_NONE;
}
static int op_is_rrr(int op) { return op_magn(op) == 7; }
static uint32_t op_prefix_insn(int op) {
    for (int i = 0; i < R_NTAB; i++) if (r_tab[i].op == op) { int pbits = 11 - r_tab[i].magn; return r_tab[i].val << (32 - pbits); }
    return 0;
}
static int imm_bits(int k) { return k == F_I7 ? 7 : k == F_I8 ? 8 : k == F_I10 ? 10 : k == F_I16 ? 16 : k == F_I18 ? 18 : 0; }
static int imm_shift(int k) { return (k == F_I16 || k == F_I18) ? 7 : 14; }
#define NPAT_ALIAS 81
#define NPAT_TOTAL (NPAT_ALIAS + 30)
/* regs used by alias patterns */
static const int ALIAS_REG[3] = { 5, 6, 7 };

static uint32_t build_insn(int op, int pat, uint32_t imm, int* used_regs /*[4]: rt ra rb rc, -1 unused*/) {
    int k = op_imm_kind(op), rrr = op_is_rrr(op);
    uint32_t insn = op_prefix_insn(op);
    int f[4];   /* rt, ra, rb, rc(=rt4 dest in RRR) */
    if (pat < NPAT_ALIAS) { int p = pat; for (int i = 0; i < 4; i++) { f[i] = ALIAS_REG[p % 3]; p /= 3; } }
    else for (int i = 0; i < 4; i++) { f[i] = (int)(rnd() % 128); if (f[i] == 1) f[i] = 2; }   /* r1: RPCS3's CBX family asserts on a misaligned SP */
    for (int i = 0; i < 4; i++) used_regs[i] = -1;
    /* low bits not otherwise assigned stay random */
    uint32_t rest = rnd();
    int lo_bits_top;                          /* bits below the opcode prefix */
    { int pbits = 11 - op_magn(op); lo_bits_top = 32 - pbits; }
    uint32_t lowmask = (lo_bits_top >= 32) ? ~0u : ((1u << lo_bits_top) - 1);
    insn |= rest & lowmask;
    if (rrr) {
        insn = (insn & ~(0x7Fu << 21)) | ((uint32_t)f[0] << 21); used_regs[0] = f[0];
        insn = (insn & ~(0x7Fu << 7))  | ((uint32_t)f[1] << 7);  used_regs[1] = f[1];
        insn = (insn & ~(0x7Fu << 14)) | ((uint32_t)f[2] << 14); used_regs[2] = f[2];
        insn = (insn & ~0x7Fu)         | (uint32_t)f[3];         used_regs[3] = f[3];
    } else {
        insn = (insn & ~0x7Fu) | (uint32_t)f[0]; used_regs[0] = f[0];
        if (k != F_I16 && k != F_I18) { insn = (insn & ~(0x7Fu << 7)) | ((uint32_t)f[1] << 7); used_regs[1] = f[1]; }
        if (k == F_NONE) { insn = (insn & ~(0x7Fu << 14)) | ((uint32_t)f[2] << 14); used_regs[2] = f[2]; }
        if (k != F_NONE) { int b = imm_bits(k), s = imm_shift(k); uint32_t m = ((1u << b) - 1) << s; insn = (insn & ~m) | ((imm << s) & m); }
    }
    switch (op) { case R_BI: case R_BISL: case R_IRET: case R_BISLED: case R_BIZ: case R_BINZ: case R_BIHZ: case R_BIHNZ: case R_HBR:
        if ((insn & (3u << 18)) == (3u << 18)) insn &= ~(1u << 19);   /* e&&d is architecturally undefined (RPCS3 throws) */ break; default: break; }
    if (op == R_RDCH || op == R_WRCH || op == R_RCHCNT) { used_regs[1] = -1; insn = (insn & ~(0x7Fu << 7)) | ((rnd() % 128) << 7); }
    return insn;
}

/* ======================================================================================== */
/* comparison                                                                                */
/* ======================================================================================== */
typedef struct { long trials, fail, skipped_oracle, hand_fallback, audit_fail; } OpStat;
static int g_audit;

static void oracle_from_hand(const Ref* R, uint32_t insn, oracle_result* o) {
    memset(o, 0, sizeof *o); o->ok = 1;
    for (int r = 0; r < 128; r++) memcpy(o->gpr[r], g_gbe[r], 16);
    if (R->dest >= 0) memcpy(o->gpr[R->dest], R->val.b, 16);
    o->next_pc = R->next; o->halted = R->halt; o->stopped = R->stop; o->stop_code = R->stop_code;
    if (R->ch_op) { o->ch_ops = 1; o->ch_no = R->ch_no; }
    if (R->st) { o->mem = 1; o->mem_addr = R->st_addr; memcpy(o->mem_quad, R->st_val.b, 16); }
    (void)insn;
}

static void qhex(char* b, const uint8_t* q) { sprintf(b, "%02X%02X%02X%02X_%02X%02X%02X%02X_%02X%02X%02X%02X_%02X%02X%02X%02X", q[0],q[1],q[2],q[3],q[4],q[5],q[6],q[7],q[8],q[9],q[10],q[11],q[12],q[13],q[14],q[15]); }

/* returns 0 if equal, else writes a description */
static int compare(const oracle_result* e, const oracle_result* g, char* why, size_t wn) {
    if (e->halted != g->halted) { snprintf(why, wn, "halt: got %d exp %d", g->halted, e->halted); return 1; }
    if (e->stopped != g->stopped || (e->stopped && e->stop_code != g->stop_code)) { snprintf(why, wn, "stop: got %d/%X exp %d/%X", g->stopped, g->stop_code, e->stopped, e->stop_code); return 1; }
    for (int r = 0; r < 128; r++) if (memcmp(e->gpr[r], g->gpr[r], 16)) {
        char a[64], b[64]; qhex(a, g->gpr[r]); qhex(b, e->gpr[r]); snprintf(why, wn, "r%d got %s exp %s", r, a, b); return 1; }
    if (e->mem != g->mem || (e->mem && (e->mem_addr != g->mem_addr || memcmp(e->mem_quad, g->mem_quad, 16)))) {
        char a[64], b[64]; qhex(a, g->mem_quad); qhex(b, e->mem_quad); snprintf(why, wn, "mem got %d@%05X %s exp %d@%05X %s", g->mem, g->mem_addr, a, e->mem, e->mem_addr, b); return 1; }
    if (e->ch_ops != g->ch_ops || (e->ch_ops && (e->ch_no != g->ch_no || e->ch_out != g->ch_out))) { snprintf(why, wn, "channel: got n=%d ch=%u v=%08X exp n=%d ch=%u v=%08X", g->ch_ops, g->ch_no, g->ch_out, e->ch_ops, e->ch_no, e->ch_out); return 1; }
    if (!e->halted && e->next_pc != g->next_pc) { snprintf(why, wn, "pc got %05X exp %05X", g->next_pc, e->next_pc); return 1; }
    return 0;
}

/* backend: run one instruction on g_ctx (registers already loaded); return nonzero if it halted/stopped */
typedef int (*backend_fn)(spu_context* ctx, uint32_t insn, uint32_t pc, void* user);
static int backend_interp(spu_context* ctx, uint32_t insn, uint32_t pc, void* user) {
    (void)user; uint32_t m = pc & 0x3FFFC;
    ctx->ls[m] = insn >> 24; ctx->ls[m+1] = insn >> 16; ctx->ls[m+2] = insn >> 8; ctx->ls[m+3] = insn;
    ctx->pc = pc; return spu_step(ctx);
}

static long g_total_trials, g_total_fail, g_total_skip, g_total_hand, g_total_audit;
static int  g_ops_done;
static char g_hand_ops[1024], g_skip_ops[1024];

/* Execute one trial. Returns 1 on mismatch. */
static int one_trial(int op, uint32_t insn, uint32_t pc, backend_fn be, void* user, OpStat* st, int* printed, const char* nm) {
    uint32_t m = pc & 0x3FFFC; uint8_t patch[4] = { insn >> 24, insn >> 16, insn >> 8, insn }, sv[4];
    uint32_t srr0 = rnd(), evt = rnd() & 1, ch_in = int_word(), ch_cnt = int_word();
    memcpy(sv, g_ls0 + m, 4);
    /* RPCS3 oracle */
    oracle_result ex;
    rpcs3_oracle_poke(m, patch, 4);
    int ok = rpcs3_oracle_run(insn, pc, (const uint8_t (*)[16])g_gbe, srr0, ch_in, ch_cnt, evt, &ex);
    rpcs3_oracle_poke(m, sv, 4);
    if (ok && (op == R_CSFLT || op == R_CUFLT)) {
        /* Known RPCS3 precise-path bug: a zero source lane is rescaled like a nonzero one, so for i8 > 155 it yields a
         * nonzero float (exponent = i8-155). int->float of 0 is 0 for every scale; expect that. */
        int ra = (insn >> 7) & 0x7F, rt = insn & 0x7F;
        for (int i = 0; i < 4; i++) if (g_orig[ra]._u32[i] == 0) memset(&ex.gpr[rt][4*i], 0, 4);
    }
    /* hand-written ISA reference (fallback where RPCS3 has no implementation; --audit cross-check) */
    memcpy(g_ls0 + m, patch, 4);
    Ref R = ref_exec(op, insn, pc, g_orig, g_ls0, srr0, evt);
    memcpy(g_ls0 + m, sv, 4);
    oracle_result hr; int have_hand = (R.next != ~0u);
    if (have_hand) oracle_from_hand(&R, insn, &hr);
    char why[300]; why[0] = 0;
    if (g_audit) {
        if (!ok || !have_hand) return 0;
        oracle_result g2 = hr;
        if (R.ch_op == 1 || R.ch_op == 3) memcpy(g2.gpr[insn & 0x7F], ex.gpr[insn & 0x7F], 16);   /* payload not modelled */
        if (R.ch_op == 2) g2.ch_out = ex.ch_out;
        st->trials++;
        if (compare(&ex, &g2, why, sizeof why)) { st->audit_fail++; if ((*printed)++ < 3) printf("  AUDIT %s insn=%08X pc=%05X: hand-ref vs RPCS3: %s\n", nm, insn, pc, why); return 1; }
        return 0;
    }
    int hand = 0;
    if (!ok) {
        st->skipped_oracle++;
        if (!have_hand) return 0;
        ex = hr; hand = 1; st->hand_fallback++;
    }
    /* ours */
    memcpy(g_ctx.gpr, g_orig, sizeof g_orig);
    g_ctx.srr0 = srr0; g_ctx.event_mask = evt ? 0xFF : 0; g_ctx.event_status = 0xFF; g_ctx.status = SPU_STATUS_RUNNING; g_ctx.stop_code = 0;
    g_ch_n = 0; memset(&g_ch_val, 0, sizeof g_ch_val); g_ch_val._u32[0] = ch_in; g_ch_cnt = ch_cnt;
    int halted = be(&g_ctx, insn, pc, user);
    oracle_result got; memset(&got, 0, sizeof got); got.ok = 1;
    for (int r = 0; r < 128; r++) bsw_store(got.gpr[r], &g_ctx.gpr[r]);
    got.halted = halted && (g_ctx.status & SPU_STATUS_STOPPED_BY_HALT);
    got.stopped = halted && (g_ctx.status & SPU_STATUS_STOPPED_BY_STOP); got.stop_code = got.stopped ? g_ctx.stop_code : 0;
    got.next_pc = (uint32_t)g_ctx.pc & 0x3FFFC;
    got.ch_ops = (int)g_ch_n; got.ch_no = g_ch_n ? g_ch_last : 0; got.ch_out = (g_ch_n && op == R_WRCH) ? g_ch_val._u32[0] : 0;
    oracle_result e = ex;
    if (e.ch_ops && op != R_WRCH) e.ch_out = 0;
    if (!e.ch_ops) { e.ch_no = 0; e.ch_out = 0; }
    if (e.mem) { got.mem = 1; got.mem_addr = e.mem_addr; memcpy(got.mem_quad, g_ctx.ls + e.mem_addr, 16); }
    st->trials++;
    int bad = compare(&e, &got, why, sizeof why);
    /* restore ours' LS from the pristine copy: instruction word + any touched quad */
    memcpy(g_ctx.ls + m, sv, 4);
    if (e.mem) memcpy(g_ctx.ls + e.mem_addr, g_ls0 + e.mem_addr, 16);
    if (bad) { st->fail++; if ((*printed)++ < show_limit()) { printf("  MISMATCH %s insn=%08X pc=%05X%s: %s\n", nm, insn, pc, hand ? " [vs hand-ref]" : "", why);
        char x[64], y[64], z[64], w[64]; qhex(x, g_gbe[(insn >> 7) & 0x7F]); qhex(y, g_gbe[(insn >> 14) & 0x7F]); qhex(z, g_gbe[insn & 0x7F]); qhex(w, g_gbe[(insn >> 21) & 0x7F]);
        printf("      operands: ra=%s rb=%s rt/rc=%s rt4=%s\n", x, y, z, w); } }
    return bad;
}

/* Run every trial of one op. */
static int run_op(int op, long scale, backend_fn be, void* user) {
    char nm[32]; lname(op, nm);
    OpStat st; memset(&st, 0, sizeof st); int printed = 0;
    int k = op_imm_kind(op), kind = op_kind(op);
    long nimm = k == F_NONE ? 1 : (1L << imm_bits(k));
    long reps = k == F_NONE ? (NPAT_TOTAL * 6L) : (k == F_I16 ? 1 : k == F_I18 ? 1 : 4);
    if (kind != 0) reps *= (k == F_NONE ? 4 : 6);
    reps *= scale;
    if (k == F_I18 || k == F_I16) { if (scale > 1) reps = scale; }
    long pat = 0;
    for (long im = 0; im < nimm; im++) for (long rp = 0; rp < reps; rp++) {
        int used[4]; int p = (int)(pat++ % NPAT_TOTAL);
        uint32_t insn = build_insn(op, p, (uint32_t)im, used);
        /* operands: refresh the registers named by the instruction and the alias registers */
        for (int i = 0; i < 4; i++) if (used[i] >= 0) fill_reg(used[i], (op == R_CSFLT || op == R_CUFLT) ? 0 : kind);
        for (int i = 0; i < 3; i++) if ((rnd() & 3) == 0) fill_reg(ALIAS_REG[i], kind);
        if ((rnd() & 7) == 0 && used[1] >= 0 && used[2] >= 0) {   /* equal / near-equal operands exercise compares */
            memcpy(&g_orig[used[2]], &g_orig[used[1]], 16); if (rnd() & 1) g_orig[used[2]]._u8[rnd() & 15] ^= (uint8_t)(1 + rnd() % 255);
            bsw_store(g_gbe[used[2]], &g_orig[used[2]]); }
        uint32_t pc = (rnd() % 8 == 0) ? ((rnd() & 1) ? 0x3FFFC : 0) : (rnd() & 0x3FFFC);
        one_trial(op, insn, pc, be, user, &st, &printed, nm);
    }
    g_total_trials += st.trials; g_total_fail += st.fail + st.audit_fail; g_total_skip += st.skipped_oracle; g_total_hand += st.hand_fallback;
    if (st.hand_fallback && strlen(g_hand_ops) < 900) { strcat(g_hand_ops, nm); strcat(g_hand_ops, " "); }
    if (st.skipped_oracle && !st.hand_fallback && strlen(g_skip_ops) < 900) { strcat(g_skip_ops, nm); strcat(g_skip_ops, " "); }
    g_ops_done++;
    printf("%-9s %-10s %9ld trials  %ld mismatches%s\n", (st.fail || st.audit_fail) ? "FAIL" : "ok", nm, st.trials, st.fail + st.audit_fail,
           st.hand_fallback ? "  (RPCS3 has no impl: compared to hand-written ISA reference)" : st.skipped_oracle ? "  (some trials skipped: RPCS3 undefined)" : "");
    return st.fail + st.audit_fail != 0;
}

#ifdef LIFTED_CASES_INC
/* backend: the lifter's emitted C for exactly this instruction word. user = case index. */
static int backend_lifted(spu_context* ctx, uint32_t insn, uint32_t pc, void* user) {
    long idx = (long)user;
    uint32_t m = pc & 0x3FFFC; ctx->ls[m] = insn >> 24; ctx->ls[m+1] = insn >> 16; ctx->ls[m+2] = insn >> 8; ctx->ls[m+3] = insn;   /* code is in LS (lqr of own word) */
    g_spu_trampoline_fn = 0; g_lc_called = 0; ctx->pc = pc;
    g_lc_cases[idx].fn(ctx);
    if (g_lc_called) ctx->pc = g_lc_target;               /* call / indirect-call: the callee entry */
    else if (!g_spu_trampoline_fn && !(ctx->status & (SPU_STATUS_STOPPED_BY_STOP | SPU_STATUS_STOPPED_BY_HALT))) ctx->pc = pc + 4;
    else if (ctx->status & SPU_STATUS_STOPPED_BY_STOP) ctx->pc = (pc + 4) & 0x3FFFC;
    return (ctx->status & (SPU_STATUS_STOPPED_BY_STOP | SPU_STATUS_STOPPED_BY_HALT)) != 0;
}
static int run_lifted_cases(long scale) {
    OpStat all; memset(&all, 0, sizeof all); int failing = 0;
    int cur_op = -1; OpStat st; int printed = 0; char nm[32] = "";
    for (long ci = 0; ci <= LC_NCASES; ci++) {
        int op = ci < LC_NCASES ? ref_decode(g_lc_cases[ci].insn) : -2;
        if (op != cur_op) {
            if (cur_op > 0) { g_ops_done++; g_total_trials += st.trials; g_total_fail += st.fail; g_total_skip += st.skipped_oracle; g_total_hand += st.hand_fallback;
                printf("%-9s %-10s %9ld lifted trials  %ld mismatches\n", st.fail ? "FAIL" : "ok", nm, st.trials, st.fail); failing += st.fail != 0; }
            memset(&st, 0, sizeof st); printed = 0; cur_op = op; if (op > 0) lname(op, nm);
        }
        if (ci == LC_NCASES) break;
        uint32_t insn = g_lc_cases[ci].insn, pc = g_lc_cases[ci].pc; int kind = op_kind(op);
        for (long t = 0; t < 24 * scale * (kind ? 3 : 1); t++) {
            int ra = (insn >> 7) & 0x7F, rb = (insn >> 14) & 0x7F, rt = insn & 0x7F, rt4 = (insn >> 21) & 0x7F;
            int regs[4] = { ra, rb, rt, rt4 };
            for (int i = 0; i < 4; i++) fill_reg(regs[i], (op == R_CSFLT || op == R_CUFLT) ? 0 : kind);
            for (int i = 0; i < 3; i++) if ((rnd() & 3) == 0) fill_reg(ALIAS_REG[i], kind);
            if ((rnd() & 7) == 0) { memcpy(&g_orig[rb], &g_orig[ra], 16); if (rnd() & 1) g_orig[rb]._u8[rnd() & 15] ^= (uint8_t)(1 + rnd() % 255); bsw_store(g_gbe[rb], &g_orig[rb]); }
            one_trial(op, insn, pc, backend_lifted, (void*)ci, &st, &printed, nm);
        }
    }
    return failing;
}
#endif

/* ---- decode cross-check ---- */
static long decode_check(void) {
    long bad = 0, n = 0; spu_ins d;
    for (uint32_t p = 0; p < 2048; p++) for (int k = 0; k < 64; k++) {
        uint32_t insn = (p << 21) | (rnd() & 0x1FFFFF);
        if (k == 0) insn = p << 21;
        if (k == 1) insn = (p << 21) | 0x1FFFFF;
        spu_decode1(insn, 0, &d); n++;
        int rop = ref_decode(insn); const char* have = d.op == SPU_word ? "?" : spu_op_name[d.op]; char nm[32]; lname(rop, nm);
        int match = (rop == R_UNK) ? (d.op == SPU_word) : (d.op != SPU_word && !strcmp(have, nm));
        if (!match) { if (bad < 12) printf("  DECODE %08X: interp '%s' ref '%s'\n", insn, have, rop == R_UNK ? "?" : nm); bad++; }
    }
    for (long i = 0; i < 2000000; i++) { uint32_t insn = rnd() ^ (rnd() << 16); spu_decode1(insn, 0, &d); n++;
        int rop = ref_decode(insn); const char* have = d.op == SPU_word ? "?" : spu_op_name[d.op]; char nm[32]; lname(rop, nm);
        int match = (rop == R_UNK) ? (d.op == SPU_word) : (d.op != SPU_word && !strcmp(have, nm));
        if (!match) { if (bad < 12) printf("  DECODE %08X: interp '%s' ref '%s'\n", insn, have, rop == R_UNK ? "?" : nm); bad++; } }
    printf("decode cross-check vs RPCS3 opcode table: %ld words, %ld mismatches\n", n, bad);
    return bad;
}

/* Deterministic sample of instruction words for lifted mode: every op, alias patterns, boundary + random immediates. */
static void emit_cases(long scale) {
    for (int op = 1; op < R_COUNT; op++) {
        if (op_magn(op) < 0) continue;
        int k = op_imm_kind(op), used[4];
        long n = k == F_NONE ? NPAT_TOTAL : 100 * scale;
        for (long c = 0; c < n; c++) {
            uint32_t imm = 0;
            if (k != F_NONE) {
                int b = imm_bits(k); uint32_t mask = (1u << b) - 1, h = 1u << (b - 1);
                static const uint32_t sp[] = { 0, 1, 2, 3, 4, 7, 8, 15, 16, 31, 32, 63, 64, 127, 128, 255, 256, 511, 512, 1023 };
                if (c < 24) { uint32_t q = c % 12; imm = q < 4 ? q : q < 8 ? mask - (q - 4) : q == 8 ? h : q == 9 ? h - 1 : q == 10 ? h + 1 : mask >> 1; if (c >= 12) imm = sp[c % 20]; }
                else imm = rnd();
                imm &= mask;
            }
            int pat = (int)(c % NPAT_TOTAL);
            uint32_t insn = build_insn(op, pat, imm, used);
            switch (op) { case R_BI: case R_BISL: case R_IRET: case R_BISLED: case R_BIZ: case R_BINZ: case R_BIHZ: case R_BIHNZ:
                if (((insn >> 7) & 0x7F) == 0) insn |= 2u << 7; break; default: break; }   /* bi $r0 is the lifter's function-return idiom, not a plain jump */
            uint32_t pc = (rnd() % 8 == 0) ? ((rnd() & 1) ? 0x3FFFC : 0) : (rnd() & 0x3FFFC);
            /* skip direct branches to themselves (the lifter turns them into goto/halt idioms) */
            { int16_t i16 = (int16_t)((insn >> 7) & 0xFFFF); uint32_t t = 0xFFFFFFFFu;
              if (op == R_BR || op == R_BRSL || op == R_BRZ || op == R_BRNZ || op == R_BRHZ || op == R_BRHNZ) t = (pc + (uint32_t)(i16 * 4)) & 0x3FFFC;
              if (op == R_BRA || op == R_BRASL) t = (uint32_t)(i16 * 4) & 0x3FFFC;
              if (t == pc) continue; }
            printf("%08X %05X\n", insn, pc);
        }
    }
}

int main(int argc, char** argv) {
    long scale = 1; const char* only = 0; int npos = 0, emit = 0, lifted = 0;
    for (int i = 1; i < argc; i++) {
        if (!strcmp(argv[i], "--audit")) g_audit = 1;
        else if (!strcmp(argv[i], "--emit-cases")) emit = 1;
        else if (!strcmp(argv[i], "--lifted")) lifted = 1;
        else if (!strcmp(argv[i], "--op") && i + 1 < argc) only = argv[++i];
        else if (argv[i][0] != '-') { if (!npos++) scale = atol(argv[i]); else g_rng ^= (uint64_t)atoll(argv[i]) * 0x2545F4914F6CDD1Dull; }
    }
    if (emit) { emit_cases(scale); return 0; }
    spu_context_init(&g_ctx, 0);
    for (int i = 0; i < 0x40000; i++) g_ctx.ls[i] = (uint8_t)rnd();
    memcpy(g_ls0, g_ctx.ls, sizeof g_ls0);
    rpcs3_oracle_set_ls(g_ls0);
    for (int r = 0; r < 128; r++) fill_reg(r, 0);
    long dbad = (g_audit || lifted) ? 0 : decode_check();
    int failing = 0;
#ifdef LIFTED_CASES_INC
    if (lifted) {
        freopen("/dev/null", "w", stderr);   /* the lifter's halt-assert traces */
        failing += run_lifted_cases(scale);
        if (memcmp(g_ctx.ls, g_ls0, sizeof g_ls0)) { printf("LS corrupted\n"); g_total_fail++; }
        printf("lifted cases: %d  trials: %ld  mismatches: %ld\n", LC_NCASES, g_total_trials, g_total_fail);
        printf("RPCS3 undefined/unimplemented trials: %ld (compared to the hand-written ISA reference instead: %s; not compared at all: %s)\n", g_total_skip, g_hand_ops, g_skip_ops);
        printf("spu_lifted_diff_test: %s\n", g_total_fail ? "FAIL" : "PASS");
        return g_total_fail ? 1 : 0;
    }
#endif
    if (lifted) { printf("built without lifted cases (see build_diff_test.sh --lifted)\n"); return 2; }
    for (int op = 1; op < R_COUNT; op++) {
        char nm[32]; lname(op, nm);
        if (only && strcmp(only, nm)) continue;
        if (op_magn(op) < 0) continue;
        failing += run_op(op, scale, backend_interp, 0);
        if ((op & 7) == 0) for (int r = 0; r < 128; r++) fill_reg(r, 0);
        if (memcmp(g_ctx.ls, g_ls0, sizeof g_ls0)) { printf("LS corrupted after %s\n", nm); memcpy(g_ctx.ls, g_ls0, sizeof g_ls0); g_total_fail++; }
    }
    printf("ops: %d  trials: %ld  mismatches: %ld  decode mismatches: %ld\n", g_ops_done, g_total_trials, g_total_fail, dbad);
    printf("RPCS3 undefined/unimplemented trials: %ld (compared to the hand-written ISA reference instead: %s; not compared at all: %s)\n", g_total_skip, g_hand_ops, g_skip_ops);
    int okk = !g_total_fail && !dbad;
    printf("spu_interp_diff_test%s: %s\n", g_audit ? " (audit hand-ref vs RPCS3)" : "", okk ? "PASS" : "FAIL");
    return okk ? 0 : 1;
}
