/* generated by gen_test_torture.py */
static const unsigned TORTURE_EXPECTED[] = { 0x0AA10001u, 0x0AA10002u, 0x0AA10003u, 0x0AA10004u, 0x0AA10005u, 0x0AA10006u, 0x0AA10007u, 0x0AA10008u };
enum { TORTURE_EXPECTED_N = 8 };
